INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('AED', 784, 2, 'United Arab Emirates dirham');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('AFN', 971, 2, 'Afghan afghani');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('ALL', 008, 2, 'Albanian lek');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('AMD', 051, 2, 'Armenian dram');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('ANG', 532, 2, 'Netherlands Antillean guilder');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('AOA', 973, 2, 'Angolan kwanza');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('ARS', 032, 2, 'Argentine peso');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('AUD', 036, 2, 'Australian dollar');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('AWG', 533, 2, 'Aruban florin');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('AZN', 944, 2, 'Azerbaijani manat');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('BAM', 977, 2, 'Bosnia and Herzegovina convertible mark');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('BBD', 052, 2, 'Barbados dollar');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('BDT', 050, 2, 'Bangladeshi taka');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('BGN', 975, 2, 'Bulgarian lev');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('BHD', 048, 3, 'Bahraini dinar');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('BIF', 108, 0, 'Burundian franc');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('BMD', 060, 2, 'Bermudian dollar');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('BND', 096, 2, 'Brunei dollar');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('BOB', 068, 2, 'Boliviano');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('BOV', 984, 2, 'Bolivian Mvdol (funds code)');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('BRL', 986, 2, 'Brazilian real');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('BSD', 044, 2, 'Bahamian dollar');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('BTN', 064, 2, 'Bhutanese ngultrum');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('BWP', 072, 2, 'Botswana pula');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('BYN', 933, 2, 'Belarusian ruble');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('BZD', 084, 2, 'Belize dollar');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('CAD', 124, 2, 'Canadian dollar');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('CDF', 976, 2, 'Congolese franc Republic of the Congo');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('CHE', 947, 2, 'WIR euro (complementary currency)');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('CHF', 756, 2, 'Swiss franc');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('CHW', 948, 2, 'WIR franc (complementary currency)');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('CLF', 990, 4, 'Unidad de Fomento (funds code)');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('CLP', 152, 0, 'Chilean peso');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('CNY', 156, 2, 'Chinese yuan');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('COP', 170, 2, 'Colombian peso');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('COU', 970, 2, 'Unidad de Valor Real (UVR) (funds code)');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('CRC', 188, 2, 'Costa Rican colon');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('CUC', 931, 2, 'Cuban convertible peso');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('CUP', 192, 2, 'Cuban peso');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('CVE', 132, 2, 'Cape Verdean escudo');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('CZK', 203, 2, 'Czech koruna');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('DJF', 262, 0, 'Djiboutian franc');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('DKK', 208, 2, 'Danish krone');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('DOP', 214, 2, 'Dominican peso');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('DZD', 012, 2, 'Algerian dinar');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('EGP', 818, 2, 'Egyptian pound');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('ERN', 232, 2, 'Eritrean nakfa');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('ETB', 230, 2, 'Ethiopian birr');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('EUR', 978, 2, 'Euro');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('FJD', 242, 2, 'Fiji dollar');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('FKP', 238, 2, 'Falkland Islands pound');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('GBP', 826, 2, 'Pound sterling');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('GEL', 981, 2, 'Georgian lari');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('GHS', 936, 2, 'Ghanaian cedi');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('GIP', 292, 2, 'Gibraltar pound');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('GMD', 270, 2, 'Gambian dalasi');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('GNF', 324, 0, 'Guinean franc');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('GTQ', 320, 2, 'Guatemalan quetzal');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('GYD', 328, 2, 'Guyanese dollar');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('HKD', 344, 2, 'Hong Kong dollar');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('HNL', 340, 2, 'Honduran lempira');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('HRK', 191, 2, 'Croatian kuna');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('HTG', 332, 2, 'Haitian gourde');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('HUF', 348, 2, 'Hungarian forint');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('IDR', 360, 2, 'Indonesian rupiah');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('ILS', 376, 2, 'Israeli new shekel');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('INR', 356, 2, 'Indian rupee');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('IQD', 368, 3, 'Iraqi dinar');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('IRR', 364, 2, 'Iranian rial');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('ISK', 352, 0, 'Icelandic króna');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('JMD', 388, 2, 'Jamaican dollar');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('JOD', 400, 3, 'Jordanian dinar');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('JPY', 392, 0, 'Japanese yen');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('KES', 404, 2, 'Kenyan shilling');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('KGS', 417, 2, 'Kyrgyzstani som');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('KHR', 116, 2, 'Cambodian riel');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('KMF', 174, 0, 'Comoro franc');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('KPW', 408, 2, 'North Korean won');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('KRW', 410, 0, 'South Korean won');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('KWD', 414, 3, 'Kuwaiti dinar');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('KYD', 136, 2, 'Cayman Islands dollar');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('KZT', 398, 2, 'Kazakhstani tenge');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('LAK', 418, 2, 'Lao kip');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('LBP', 422, 2, 'Lebanese pound');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('LKR', 144, 2, 'Sri Lankan rupee');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('LRD', 430, 2, 'Liberian dollar');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('LSL', 426, 2, 'Lesotho loti');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('LYD', 434, 3, 'Libyan dinar');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('MAD', 504, 2, 'Moroccan dirham');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('MDL', 498, 2, 'Moldovan leu');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('MGA', 969, 2, 'Malagasy ariary');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('MKD', 807, 2, 'Macedonian denar');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('MMK', 104, 2, 'Myanmar kyat');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('MNT', 496, 2, 'Mongolian tögrög');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('MOP', 446, 2, 'Macanese pataca');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('MRU', 929, 2, 'Mauritanian ouguiya');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('MUR', 480, 2, 'Mauritian rupee');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('MVR', 462, 2, 'Maldivian rufiyaa');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('MWK', 454, 2, 'Malawian kwacha');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('MXN', 484, 2, 'Mexican peso');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('MXV', 979, 2, 'Mexican Unidad de Inversion (UDI) (funds code)');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('MYR', 458, 2, 'Malaysian ringgit');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('MZN', 943, 2, 'Mozambican metical');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('NAD', 516, 2, 'Namibian dollar');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('NGN', 566, 2, 'Nigerian naira');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('NIO', 558, 2, 'Nicaraguan córdoba');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('NOK', 578, 2, 'Norwegian krone');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('NPR', 524, 2, 'Nepalese rupee');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('NZD', 554, 2, 'New Zealand dollar');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('OMR', 512, 3, 'Omani rial');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('PAB', 590, 2, 'Panamanian balboa');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('PEN', 604, 2, 'Peruvian sol');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('PGK', 598, 2, 'Papua New Guinean kina');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('PHP', 608, 2, 'Philippine peso');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('PKR', 586, 2, 'Pakistani rupee');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('PLN', 985, 2, 'Polish złoty');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('PYG', 600, 0, 'Paraguayan guaraní');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('QAR', 634, 2, 'Qatari riyal');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('RON', 946, 2, 'Romanian leu');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('RSD', 941, 2, 'Serbian dinar');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('RUB', 643, 2, 'Russian ruble');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('RWF', 646, 0, 'Rwandan franc');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('SAR', 682, 2, 'Saudi riyal');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('SBD', 090, 2, 'Solomon Islands dollar');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('SCR', 690, 2, 'Seychelles rupee');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('SDG', 938, 2, 'Sudanese pound');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('SEK', 752, 2, 'Swedish krona/kronor');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('SGD', 702, 2, 'Singapore dollar');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('SHP', 654, 2, 'Saint Helena pound');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('SLL', 694, 2, 'Sierra Leonean leone');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('SOS', 706, 2, 'Somali shilling');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('SRD', 968, 2, 'Surinamese dollar');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('SSP', 728, 2, 'South Sudanese pound');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('STN', 930, 2, 'São Tomé and Príncipe dobra');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('SVC', 222, 2, 'Salvadoran colón');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('SYP', 760, 2, 'Syrian pound');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('SZL', 748, 2, 'Swazi lilangeni');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('THB', 764, 2, 'Thai baht');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('TJS', 972, 2, 'Tajikistani somoni');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('TMT', 934, 2, 'Turkmenistan manat');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('TND', 788, 3, 'Tunisian dinar');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('TOP', 776, 2, 'Tongan paʻanga');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('TRY', 949, 2, 'Turkish lira');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('TTD', 780, 2, 'Trinidad and Tobago dollar');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('TWD', 901, 2, 'New Taiwan dollar');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('TZS', 834, 2, 'Tanzanian shilling');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('UAH', 980, 2, 'Ukrainian hryvnia');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('UGX', 800, 0, 'Ugandan shilling');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('USD', 840, 2, 'United States dollar');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('USN', 997, 2, 'United States dollar (next day) (funds code)');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('UYI', 940, 0, 'Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('UYU', 858, 2, 'Uruguayan peso');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('UYW', 927, 4, 'Unidad previsional');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('UZS', 860, 2, 'Uzbekistan som');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('VES', 928, 2, 'Venezuelan bolívar soberano');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('VND', 704, 0, 'Vietnamese đồng');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('VUV', 548, 0, 'Vanuatu vatu');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('WST', 882, 2, 'Samoan tala');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('XAF', 950, 0, 'CFA franc BEAC');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('XAG', 961, null, 'Silver (one troy ounce)');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('XAU', 959, null, 'Gold (one troy ounce)');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('XBA', 955, null, 'European Composite Unit (EURCO) (bond market unit)');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('XBB', 956, null, 'European Monetary Unit (E.M.U.-6) (bond market unit)');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('XBC', 957, null, 'European Unit of Account 9 (E.U.A.-9) (bond market unit)');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('XBD', 958, null, 'European Unit of Account 17 (E.U.A.-17) (bond market unit)');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('XCD', 951, 2, 'East Caribbean dollar');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('XDR', 960, null, 'Special drawing rights');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('XOF', 952, 0, 'CFA franc BCEAO');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('XPD', 964, null, 'Palladium (one troy ounce)');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('XPF', 953, 0, 'CFP franc (franc Pacifique)');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('XPT', 962, null, 'Platinum (one troy ounce)');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('XSU', 994, null, 'SUCRE');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('XTS', 963, null, 'Code reserved for testing');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('XUA', 965, null, 'ADB Unit of Account');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('XXX', 999, null, 'No currency');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('YER', 886, 2, 'Yemeni rial');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('ZAR', 710, 2, 'South African rand');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('ZMW', 967, 2, 'Zambian kwacha');
INSERT INTO currency (code, numeric_code, minor_unit, name) VALUES ('ZWL', 932, 2, 'Zimbabwean');
