INSERT INTO country (code, code_a3, code_num) VALUES ('AF', 'AFG', '004'); -- 'Afghanistan'
INSERT INTO country (code, code_a3, code_num) VALUES ('AX', 'ALA', '248'); -- 'Åland Islands'
INSERT INTO country (code, code_a3, code_num) VALUES ('AL', 'ALB', '008'); -- 'Albania'
INSERT INTO country (code, code_a3, code_num) VALUES ('DZ', 'DZA', '012'); -- 'Algeria'
INSERT INTO country (code, code_a3, code_num) VALUES ('AS', 'ASM', '016'); -- 'American Samoa'
INSERT INTO country (code, code_a3, code_num) VALUES ('AD', 'AND', '020'); -- 'Andorra'
INSERT INTO country (code, code_a3, code_num) VALUES ('AO', 'AGO', '024'); -- 'Angola'
INSERT INTO country (code, code_a3, code_num) VALUES ('AI', 'AIA', '660'); -- 'Anguilla'
INSERT INTO country (code, code_a3, code_num) VALUES ('AQ', 'ATA', '010'); -- 'Antarctica'
INSERT INTO country (code, code_a3, code_num) VALUES ('AG', 'ATG', '028'); -- 'Antigua and Barbuda'
INSERT INTO country (code, code_a3, code_num) VALUES ('AR', 'ARG', '032'); -- 'Argentina'
INSERT INTO country (code, code_a3, code_num) VALUES ('AM', 'ARM', '051'); -- 'Armenia'
INSERT INTO country (code, code_a3, code_num) VALUES ('AW', 'ABW', '533'); -- 'Aruba'
INSERT INTO country (code, code_a3, code_num) VALUES ('AU', 'AUS', '036'); -- 'Australia'
INSERT INTO country (code, code_a3, code_num) VALUES ('AT', 'AUT', '040'); -- 'Austria'
INSERT INTO country (code, code_a3, code_num) VALUES ('AZ', 'AZE', '031'); -- 'Azerbaijan'
INSERT INTO country (code, code_a3, code_num) VALUES ('BS', 'BHS', '044'); -- 'Bahamas'
INSERT INTO country (code, code_a3, code_num) VALUES ('BH', 'BHR', '048'); -- 'Bahrain'
INSERT INTO country (code, code_a3, code_num) VALUES ('BD', 'BGD', '050'); -- 'Bangladesh'
INSERT INTO country (code, code_a3, code_num) VALUES ('BB', 'BRB', '052'); -- 'Barbados'
INSERT INTO country (code, code_a3, code_num) VALUES ('BY', 'BLR', '112'); -- 'Belarus'
INSERT INTO country (code, code_a3, code_num) VALUES ('BE', 'BEL', '056'); -- 'Belgium'
INSERT INTO country (code, code_a3, code_num) VALUES ('BZ', 'BLZ', '084'); -- 'Belize'
INSERT INTO country (code, code_a3, code_num) VALUES ('BJ', 'BEN', '204'); -- 'Benin'
INSERT INTO country (code, code_a3, code_num) VALUES ('BM', 'BMU', '060'); -- 'Bermuda'
INSERT INTO country (code, code_a3, code_num) VALUES ('BT', 'BTN', '064'); -- 'Bhutan'
INSERT INTO country (code, code_a3, code_num) VALUES ('BO', 'BOL', '068'); -- 'Bolivia, Plurinational State of'
INSERT INTO country (code, code_a3, code_num) VALUES ('BA', 'BIH', '070'); -- 'Bosnia and Herzegovina'
INSERT INTO country (code, code_a3, code_num) VALUES ('BQ', 'BES', '535'); -- 'Bonaire, Sint Eustatius and Saba'
INSERT INTO country (code, code_a3, code_num) VALUES ('BW', 'BWA', '072'); -- 'Botswana'
INSERT INTO country (code, code_a3, code_num) VALUES ('BV', 'BVT', '074'); -- 'Bouvet Island'
INSERT INTO country (code, code_a3, code_num) VALUES ('BR', 'BRA', '076'); -- 'Brazil'
INSERT INTO country (code, code_a3, code_num) VALUES ('IO', 'IOT', '086'); -- 'British Indian Ocean Territory'
INSERT INTO country (code, code_a3, code_num) VALUES ('BN', 'BRN', '096'); -- 'Brunei Darussalam'
INSERT INTO country (code, code_a3, code_num) VALUES ('BG', 'BGR', '100'); -- 'Bulgaria'
INSERT INTO country (code, code_a3, code_num) VALUES ('BF', 'BFA', '854'); -- 'Burkina Faso'
INSERT INTO country (code, code_a3, code_num) VALUES ('BI', 'BDI', '108'); -- 'Burundi'
INSERT INTO country (code, code_a3, code_num) VALUES ('KH', 'KHM', '116'); -- 'Cambodia'
INSERT INTO country (code, code_a3, code_num) VALUES ('CM', 'CMR', '120'); -- 'Cameroon'
INSERT INTO country (code, code_a3, code_num) VALUES ('CA', 'CAN', '124'); -- 'Canada'
INSERT INTO country (code, code_a3, code_num) VALUES ('CV', 'CPV', '132'); -- 'Cape Verde'
INSERT INTO country (code, code_a3, code_num) VALUES ('KY', 'CYM', '136'); -- 'Cayman Islands'
INSERT INTO country (code, code_a3, code_num) VALUES ('CF', 'CAF', '140'); -- 'Central African Republic'
INSERT INTO country (code, code_a3, code_num) VALUES ('TD', 'TCD', '148'); -- 'Chad'
INSERT INTO country (code, code_a3, code_num) VALUES ('CL', 'CHL', '152'); -- 'Chile'
INSERT INTO country (code, code_a3, code_num) VALUES ('CN', 'CHN', '156'); -- 'China'
INSERT INTO country (code, code_a3, code_num) VALUES ('CX', 'CXR', '162'); -- 'Christmas Island'
INSERT INTO country (code, code_a3, code_num) VALUES ('CC', 'CCK', '166'); -- 'Cocos (Keeling) Islands'
INSERT INTO country (code, code_a3, code_num) VALUES ('CO', 'COL', '170'); -- 'Colombia'
INSERT INTO country (code, code_a3, code_num) VALUES ('KM', 'COM', '174'); -- 'Comoros'
INSERT INTO country (code, code_a3, code_num) VALUES ('CG', 'COG', '178'); -- 'Congo'
INSERT INTO country (code, code_a3, code_num) VALUES ('CD', 'COD', '180'); -- 'Congo, the Democratic Republic of the'
INSERT INTO country (code, code_a3, code_num) VALUES ('CK', 'COK', '184'); -- 'Cook Islands'
INSERT INTO country (code, code_a3, code_num) VALUES ('CR', 'CRI', '188'); -- 'Costa Rica'
INSERT INTO country (code, code_a3, code_num) VALUES ('CI', 'CIV', '384'); -- 'Côte d'Ivoire'
INSERT INTO country (code, code_a3, code_num) VALUES ('HR', 'HRV', '191'); -- 'Croatia'
INSERT INTO country (code, code_a3, code_num) VALUES ('CU', 'CUB', '192'); -- 'Cuba'
INSERT INTO country (code, code_a3, code_num) VALUES ('CW', 'CUW', '531'); -- 'Curaçao'
INSERT INTO country (code, code_a3, code_num) VALUES ('CY', 'CYP', '196'); -- 'Cyprus'
INSERT INTO country (code, code_a3, code_num) VALUES ('CZ', 'CZE', '203'); -- 'Czech Republic'
INSERT INTO country (code, code_a3, code_num) VALUES ('DK', 'DNK', '208'); -- 'Denmark'
INSERT INTO country (code, code_a3, code_num) VALUES ('DJ', 'DJI', '262'); -- 'Djibouti'
INSERT INTO country (code, code_a3, code_num) VALUES ('DM', 'DMA', '212'); -- 'Dominica'
INSERT INTO country (code, code_a3, code_num) VALUES ('DO', 'DOM', '214'); -- 'Dominican Republic'
INSERT INTO country (code, code_a3, code_num) VALUES ('EC', 'ECU', '218'); -- 'Ecuador'
INSERT INTO country (code, code_a3, code_num) VALUES ('EG', 'EGY', '818'); -- 'Egypt'
INSERT INTO country (code, code_a3, code_num) VALUES ('SV', 'SLV', '222'); -- 'El Salvador'
INSERT INTO country (code, code_a3, code_num) VALUES ('GQ', 'GNQ', '226'); -- 'Equatorial Guinea'
INSERT INTO country (code, code_a3, code_num) VALUES ('ER', 'ERI', '232'); -- 'Eritrea'
INSERT INTO country (code, code_a3, code_num) VALUES ('EE', 'EST', '233'); -- 'Estonia'
INSERT INTO country (code, code_a3, code_num) VALUES ('SZ', 'SWZ', '748'); -- 'Eswatini'
INSERT INTO country (code, code_a3, code_num) VALUES ('ET', 'ETH', '231'); -- 'Ethiopia'
INSERT INTO country (code, code_a3, code_num) VALUES ('FK', 'FLK', '238'); -- 'Falkland Islands (Malvinas)'
INSERT INTO country (code, code_a3, code_num) VALUES ('FO', 'FRO', '234'); -- 'Faroe Islands'
INSERT INTO country (code, code_a3, code_num) VALUES ('FJ', 'FJI', '242'); -- 'Fiji'
INSERT INTO country (code, code_a3, code_num) VALUES ('FI', 'FIN', '246'); -- 'Finland'
INSERT INTO country (code, code_a3, code_num) VALUES ('FR', 'FRA', '250'); -- 'France'
INSERT INTO country (code, code_a3, code_num) VALUES ('GF', 'GUF', '254'); -- 'French Guiana'
INSERT INTO country (code, code_a3, code_num) VALUES ('PF', 'PYF', '258'); -- 'French Polynesia'
INSERT INTO country (code, code_a3, code_num) VALUES ('TF', 'ATF', '260'); -- 'French Southern Territories'
INSERT INTO country (code, code_a3, code_num) VALUES ('GA', 'GAB', '266'); -- 'Gabon'
INSERT INTO country (code, code_a3, code_num) VALUES ('GM', 'GMB', '270'); -- 'Gambia'
INSERT INTO country (code, code_a3, code_num) VALUES ('GE', 'GEO', '268'); -- 'Georgia'
INSERT INTO country (code, code_a3, code_num) VALUES ('DE', 'DEU', '276'); -- 'Germany'
INSERT INTO country (code, code_a3, code_num) VALUES ('GH', 'GHA', '288'); -- 'Ghana'
INSERT INTO country (code, code_a3, code_num) VALUES ('GI', 'GIB', '292'); -- 'Gibraltar'
INSERT INTO country (code, code_a3, code_num) VALUES ('GR', 'GRC', '300'); -- 'Greece'
INSERT INTO country (code, code_a3, code_num) VALUES ('GL', 'GRL', '304'); -- 'Greenland'
INSERT INTO country (code, code_a3, code_num) VALUES ('GD', 'GRD', '308'); -- 'Grenada'
INSERT INTO country (code, code_a3, code_num) VALUES ('GP', 'GLP', '312'); -- 'Guadeloupe'
INSERT INTO country (code, code_a3, code_num) VALUES ('GU', 'GUM', '316'); -- 'Guam'
INSERT INTO country (code, code_a3, code_num) VALUES ('GT', 'GTM', '320'); -- 'Guatemala'
INSERT INTO country (code, code_a3, code_num) VALUES ('GG', 'GGY', '831'); -- 'Guernsey'
INSERT INTO country (code, code_a3, code_num) VALUES ('GN', 'GIN', '324'); -- 'Guinea'
INSERT INTO country (code, code_a3, code_num) VALUES ('GW', 'GNB', '624'); -- 'Guinea-Bissau'
INSERT INTO country (code, code_a3, code_num) VALUES ('GY', 'GUY', '328'); -- 'Guyana'
INSERT INTO country (code, code_a3, code_num) VALUES ('HT', 'HTI', '332'); -- 'Haiti'
INSERT INTO country (code, code_a3, code_num) VALUES ('HM', 'HMD', '334'); -- 'Heard Island and McDonald Islands'
INSERT INTO country (code, code_a3, code_num) VALUES ('VA', 'VAT', '336'); -- 'Holy See (Vatican City State)'
INSERT INTO country (code, code_a3, code_num) VALUES ('HN', 'HND', '340'); -- 'Honduras'
INSERT INTO country (code, code_a3, code_num) VALUES ('HK', 'HKG', '344'); -- 'Hong Kong'
INSERT INTO country (code, code_a3, code_num) VALUES ('HU', 'HUN', '348'); -- 'Hungary'
INSERT INTO country (code, code_a3, code_num) VALUES ('IS', 'ISL', '352'); -- 'Iceland'
INSERT INTO country (code, code_a3, code_num) VALUES ('IN', 'IND', '356'); -- 'India'
INSERT INTO country (code, code_a3, code_num) VALUES ('ID', 'IDN', '360'); -- 'Indonesia'
INSERT INTO country (code, code_a3, code_num) VALUES ('IR', 'IRN', '364'); -- 'Iran, Islamic Republic of'
INSERT INTO country (code, code_a3, code_num) VALUES ('IQ', 'IRQ', '368'); -- 'Iraq'
INSERT INTO country (code, code_a3, code_num) VALUES ('IE', 'IRL', '372'); -- 'Ireland'
INSERT INTO country (code, code_a3, code_num) VALUES ('IM', 'IMN', '833'); -- 'Isle of Man'
INSERT INTO country (code, code_a3, code_num) VALUES ('IL', 'ISR', '376'); -- 'Israel'
INSERT INTO country (code, code_a3, code_num) VALUES ('IT', 'ITA', '380'); -- 'Italy'
INSERT INTO country (code, code_a3, code_num) VALUES ('JM', 'JAM', '388'); -- 'Jamaica'
INSERT INTO country (code, code_a3, code_num) VALUES ('JP', 'JPN', '392'); -- 'Japan'
INSERT INTO country (code, code_a3, code_num) VALUES ('JE', 'JEY', '832'); -- 'Jersey'
INSERT INTO country (code, code_a3, code_num) VALUES ('JO', 'JOR', '400'); -- 'Jordan'
INSERT INTO country (code, code_a3, code_num) VALUES ('KZ', 'KAZ', '398'); -- 'Kazakhstan'
INSERT INTO country (code, code_a3, code_num) VALUES ('KE', 'KEN', '404'); -- 'Kenya'
INSERT INTO country (code, code_a3, code_num) VALUES ('KI', 'KIR', '296'); -- 'Kiribati'
INSERT INTO country (code, code_a3, code_num) VALUES ('KP', 'PRK', '408'); -- 'Korea, Democratic People's Republic of'
INSERT INTO country (code, code_a3, code_num) VALUES ('KR', 'KOR', '410'); -- 'Korea, Republic of'
INSERT INTO country (code, code_a3, code_num) VALUES ('KW', 'KWT', '414'); -- 'Kuwait'
INSERT INTO country (code, code_a3, code_num) VALUES ('KG', 'KGZ', '417'); -- 'Kyrgyzstan'
INSERT INTO country (code, code_a3, code_num) VALUES ('LA', 'LAO', '418'); -- 'Lao People's Democratic Republic'
INSERT INTO country (code, code_a3, code_num) VALUES ('LV', 'LVA', '428'); -- 'Latvia'
INSERT INTO country (code, code_a3, code_num) VALUES ('LB', 'LBN', '422'); -- 'Lebanon'
INSERT INTO country (code, code_a3, code_num) VALUES ('LS', 'LSO', '426'); -- 'Lesotho'
INSERT INTO country (code, code_a3, code_num) VALUES ('LR', 'LBR', '430'); -- 'Liberia'
INSERT INTO country (code, code_a3, code_num) VALUES ('LY', 'LBY', '434'); -- 'Libya'
INSERT INTO country (code, code_a3, code_num) VALUES ('LI', 'LIE', '438'); -- 'Liechtenstein'
INSERT INTO country (code, code_a3, code_num) VALUES ('LT', 'LTU', '440'); -- 'Lithuania'
INSERT INTO country (code, code_a3, code_num) VALUES ('LU', 'LUX', '442'); -- 'Luxembourg'
INSERT INTO country (code, code_a3, code_num) VALUES ('MO', 'MAC', '446'); -- 'Macao'
INSERT INTO country (code, code_a3, code_num) VALUES ('MK', 'MKD', '807'); -- 'North Macedonia'
INSERT INTO country (code, code_a3, code_num) VALUES ('MG', 'MDG', '450'); -- 'Madagascar'
INSERT INTO country (code, code_a3, code_num) VALUES ('MW', 'MWI', '454'); -- 'Malawi'
INSERT INTO country (code, code_a3, code_num) VALUES ('MY', 'MYS', '458'); -- 'Malaysia'
INSERT INTO country (code, code_a3, code_num) VALUES ('MV', 'MDV', '462'); -- 'Maldives'
INSERT INTO country (code, code_a3, code_num) VALUES ('ML', 'MLI', '466'); -- 'Mali'
INSERT INTO country (code, code_a3, code_num) VALUES ('MT', 'MLT', '470'); -- 'Malta'
INSERT INTO country (code, code_a3, code_num) VALUES ('MH', 'MHL', '584'); -- 'Marshall Islands'
INSERT INTO country (code, code_a3, code_num) VALUES ('MQ', 'MTQ', '474'); -- 'Martinique'
INSERT INTO country (code, code_a3, code_num) VALUES ('MR', 'MRT', '478'); -- 'Mauritania'
INSERT INTO country (code, code_a3, code_num) VALUES ('MU', 'MUS', '480'); -- 'Mauritius'
INSERT INTO country (code, code_a3, code_num) VALUES ('YT', 'MYT', '175'); -- 'Mayotte'
INSERT INTO country (code, code_a3, code_num) VALUES ('MX', 'MEX', '484'); -- 'Mexico'
INSERT INTO country (code, code_a3, code_num) VALUES ('FM', 'FSM', '583'); -- 'Micronesia, Federated States of'
INSERT INTO country (code, code_a3, code_num) VALUES ('MD', 'MDA', '498'); -- 'Moldova, Republic of'
INSERT INTO country (code, code_a3, code_num) VALUES ('MC', 'MCO', '492'); -- 'Monaco'
INSERT INTO country (code, code_a3, code_num) VALUES ('MN', 'MNG', '496'); -- 'Mongolia'
INSERT INTO country (code, code_a3, code_num) VALUES ('ME', 'MNE', '499'); -- 'Montenegro'
INSERT INTO country (code, code_a3, code_num) VALUES ('MS', 'MSR', '500'); -- 'Montserrat'
INSERT INTO country (code, code_a3, code_num) VALUES ('MA', 'MAR', '504'); -- 'Morocco'
INSERT INTO country (code, code_a3, code_num) VALUES ('MZ', 'MOZ', '508'); -- 'Mozambique'
INSERT INTO country (code, code_a3, code_num) VALUES ('MM', 'MMR', '104'); -- 'Myanmar'
INSERT INTO country (code, code_a3, code_num) VALUES ('NA', 'NAM', '516'); -- 'Namibia'
INSERT INTO country (code, code_a3, code_num) VALUES ('NR', 'NRU', '520'); -- 'Nauru'
INSERT INTO country (code, code_a3, code_num) VALUES ('NP', 'NPL', '524'); -- 'Nepal'
INSERT INTO country (code, code_a3, code_num) VALUES ('NL', 'NLD', '528'); -- 'Netherlands'
INSERT INTO country (code, code_a3, code_num) VALUES ('NC', 'NCL', '540'); -- 'New Caledonia'
INSERT INTO country (code, code_a3, code_num) VALUES ('NZ', 'NZL', '554'); -- 'New Zealand'
INSERT INTO country (code, code_a3, code_num) VALUES ('NI', 'NIC', '558'); -- 'Nicaragua'
INSERT INTO country (code, code_a3, code_num) VALUES ('NE', 'NER', '562'); -- 'Niger'
INSERT INTO country (code, code_a3, code_num) VALUES ('NG', 'NGA', '566'); -- 'Nigeria'
INSERT INTO country (code, code_a3, code_num) VALUES ('NU', 'NIU', '570'); -- 'Niue'
INSERT INTO country (code, code_a3, code_num) VALUES ('NF', 'NFK', '574'); -- 'Norfolk Island'
INSERT INTO country (code, code_a3, code_num) VALUES ('MP', 'MNP', '580'); -- 'Northern Mariana Islands'
INSERT INTO country (code, code_a3, code_num) VALUES ('NO', 'NOR', '578'); -- 'Norway'
INSERT INTO country (code, code_a3, code_num) VALUES ('OM', 'OMN', '512'); -- 'Oman'
INSERT INTO country (code, code_a3, code_num) VALUES ('PK', 'PAK', '586'); -- 'Pakistan'
INSERT INTO country (code, code_a3, code_num) VALUES ('PW', 'PLW', '585'); -- 'Palau'
INSERT INTO country (code, code_a3, code_num) VALUES ('PS', 'PSE', '275'); -- 'Palestinian Territory, Occupied'
INSERT INTO country (code, code_a3, code_num) VALUES ('PA', 'PAN', '591'); -- 'Panama'
INSERT INTO country (code, code_a3, code_num) VALUES ('PG', 'PNG', '598'); -- 'Papua New Guinea'
INSERT INTO country (code, code_a3, code_num) VALUES ('PY', 'PRY', '600'); -- 'Paraguay'
INSERT INTO country (code, code_a3, code_num) VALUES ('PE', 'PER', '604'); -- 'Peru'
INSERT INTO country (code, code_a3, code_num) VALUES ('PH', 'PHL', '608'); -- 'Philippines'
INSERT INTO country (code, code_a3, code_num) VALUES ('PN', 'PCN', '612'); -- 'Pitcairn'
INSERT INTO country (code, code_a3, code_num) VALUES ('PL', 'POL', '616'); -- 'Poland'
INSERT INTO country (code, code_a3, code_num) VALUES ('PT', 'PRT', '620'); -- 'Portugal'
INSERT INTO country (code, code_a3, code_num) VALUES ('PR', 'PRI', '630'); -- 'Puerto Rico'
INSERT INTO country (code, code_a3, code_num) VALUES ('QA', 'QAT', '634'); -- 'Qatar'
INSERT INTO country (code, code_a3, code_num) VALUES ('RE', 'REU', '638'); -- 'Réunion'
INSERT INTO country (code, code_a3, code_num) VALUES ('RO', 'ROU', '642'); -- 'Romania'
INSERT INTO country (code, code_a3, code_num) VALUES ('RU', 'RUS', '643'); -- 'Russian Federation'
INSERT INTO country (code, code_a3, code_num) VALUES ('RW', 'RWA', '646'); -- 'Rwanda'
INSERT INTO country (code, code_a3, code_num) VALUES ('BL', 'BLM', '652'); -- 'Saint Barthélemy'
INSERT INTO country (code, code_a3, code_num) VALUES ('SH', 'SHN', '654'); -- 'Saint Helena, Ascension and Tristan da Cunha'
INSERT INTO country (code, code_a3, code_num) VALUES ('KN', 'KNA', '659'); -- 'Saint Kitts and Nevis'
INSERT INTO country (code, code_a3, code_num) VALUES ('LC', 'LCA', '662'); -- 'Saint Lucia'
INSERT INTO country (code, code_a3, code_num) VALUES ('MF', 'MAF', '663'); -- 'Saint Martin (French part)'
INSERT INTO country (code, code_a3, code_num) VALUES ('PM', 'SPM', '666'); -- 'Saint Pierre and Miquelon'
INSERT INTO country (code, code_a3, code_num) VALUES ('VC', 'VCT', '670'); -- 'Saint Vincent and the Grenadines'
INSERT INTO country (code, code_a3, code_num) VALUES ('WS', 'WSM', '882'); -- 'Samoa'
INSERT INTO country (code, code_a3, code_num) VALUES ('SM', 'SMR', '674'); -- 'San Marino'
INSERT INTO country (code, code_a3, code_num) VALUES ('ST', 'STP', '678'); -- 'Sao Tome and Principe'
INSERT INTO country (code, code_a3, code_num) VALUES ('SA', 'SAU', '682'); -- 'Saudi Arabia'
INSERT INTO country (code, code_a3, code_num) VALUES ('SN', 'SEN', '686'); -- 'Senegal'
INSERT INTO country (code, code_a3, code_num) VALUES ('RS', 'SRB', '688'); -- 'Serbia'
INSERT INTO country (code, code_a3, code_num) VALUES ('SC', 'SYC', '690'); -- 'Seychelles'
INSERT INTO country (code, code_a3, code_num) VALUES ('SL', 'SLE', '694'); -- 'Sierra Leone'
INSERT INTO country (code, code_a3, code_num) VALUES ('SG', 'SGP', '702'); -- 'Singapore'
INSERT INTO country (code, code_a3, code_num) VALUES ('SX', 'SXM', '534'); -- 'Sint Maarten (Dutch part)'
INSERT INTO country (code, code_a3, code_num) VALUES ('SK', 'SVK', '703'); -- 'Slovakia'
INSERT INTO country (code, code_a3, code_num) VALUES ('SI', 'SVN', '705'); -- 'Slovenia'
INSERT INTO country (code, code_a3, code_num) VALUES ('SB', 'SLB', '090'); -- 'ASolomon Islands
INSERT INTO country (code, code_a3, code_num) VALUES ('SO', 'SOM', '706'); -- 'Somalia'
INSERT INTO country (code, code_a3, code_num) VALUES ('ZA', 'ZAF', '710'); -- 'South Africa'
INSERT INTO country (code, code_a3, code_num) VALUES ('GS', 'SGS', '239'); -- 'South Georgia and the South Sandwich Islands'
INSERT INTO country (code, code_a3, code_num) VALUES ('SS', 'SSD', '728'); -- 'South Sudan'
INSERT INTO country (code, code_a3, code_num) VALUES ('ES', 'ESP', '724'); -- 'Spain'
INSERT INTO country (code, code_a3, code_num) VALUES ('LK', 'LKA', '144'); -- 'Sri Lanka'
INSERT INTO country (code, code_a3, code_num) VALUES ('SD', 'SDN', '736'); -- 'Sudan'
INSERT INTO country (code, code_a3, code_num) VALUES ('SR', 'SUR', '740'); -- 'Suriname'
INSERT INTO country (code, code_a3, code_num) VALUES ('SJ', 'SJM', '744'); -- 'Svalbard and Jan Mayen'
INSERT INTO country (code, code_a3, code_num) VALUES ('SE', 'SWE', '752'); -- 'Sweden'
INSERT INTO country (code, code_a3, code_num) VALUES ('CH', 'CHE', '756'); -- 'Switzerland'
INSERT INTO country (code, code_a3, code_num) VALUES ('SY', 'SYR', '760'); -- 'Syrian Arab Republic'
INSERT INTO country (code, code_a3, code_num) VALUES ('TW', 'TWN', '158'); -- 'Taiwan, Province of China'
INSERT INTO country (code, code_a3, code_num) VALUES ('TJ', 'TJK', '762'); -- 'Tajikistan'
INSERT INTO country (code, code_a3, code_num) VALUES ('TZ', 'TZA', '834'); -- 'Tanzania, United Republic of'
INSERT INTO country (code, code_a3, code_num) VALUES ('TH', 'THA', '764'); -- 'Thailand'
INSERT INTO country (code, code_a3, code_num) VALUES ('TL', 'TLS', '626'); -- 'Timor-Leste'
INSERT INTO country (code, code_a3, code_num) VALUES ('TG', 'TGO', '768'); -- 'Togo'
INSERT INTO country (code, code_a3, code_num) VALUES ('TK', 'TKL', '772'); -- 'Tokelau'
INSERT INTO country (code, code_a3, code_num) VALUES ('TO', 'TON', '776'); -- 'Tonga'
INSERT INTO country (code, code_a3, code_num) VALUES ('TT', 'TTO', '780'); -- 'Trinidad and Tobago'
INSERT INTO country (code, code_a3, code_num) VALUES ('TN', 'TUN', '788'); -- 'Tunisia'
INSERT INTO country (code, code_a3, code_num) VALUES ('TR', 'TUR', '792'); -- 'Turkey'
INSERT INTO country (code, code_a3, code_num) VALUES ('TM', 'TKM', '795'); -- 'Turkmenistan'
INSERT INTO country (code, code_a3, code_num) VALUES ('TC', 'TCA', '796'); -- 'Turks and Caicos Islands'
INSERT INTO country (code, code_a3, code_num) VALUES ('TV', 'TUV', '798'); -- 'Tuvalu'
INSERT INTO country (code, code_a3, code_num) VALUES ('UG', 'UGA', '800'); -- 'Uganda'
INSERT INTO country (code, code_a3, code_num) VALUES ('UA', 'UKR', '804'); -- 'Ukraine'
INSERT INTO country (code, code_a3, code_num) VALUES ('AE', 'ARE', '784'); -- 'United Arab Emirates'
INSERT INTO country (code, code_a3, code_num) VALUES ('GB', 'GBR', '826'); -- 'United Kingdom'
INSERT INTO country (code, code_a3, code_num) VALUES ('US', 'USA', '840'); -- 'United States'
INSERT INTO country (code, code_a3, code_num) VALUES ('UM', 'UMI', '581'); -- 'United States Minor Outlying Islands'
INSERT INTO country (code, code_a3, code_num) VALUES ('UY', 'URY', '858'); -- 'Uruguay'
INSERT INTO country (code, code_a3, code_num) VALUES ('UZ', 'UZB', '860'); -- 'Uzbekistan'
INSERT INTO country (code, code_a3, code_num) VALUES ('VU', 'VUT', '548'); -- 'Vanuatu'
INSERT INTO country (code, code_a3, code_num) VALUES ('VE', 'VEN', '862'); -- 'Venezuela, Bolivarian Republic of'
INSERT INTO country (code, code_a3, code_num) VALUES ('VN', 'VNM', '704'); -- 'Viet Nam'
INSERT INTO country (code, code_a3, code_num) VALUES ('VG', 'VGB', '092'); -- 'Virgin Islands, British'
INSERT INTO country (code, code_a3, code_num) VALUES ('VI', 'VIR', '850'); -- 'Virgin Islands, U.S.'
INSERT INTO country (code, code_a3, code_num) VALUES ('WF', 'WLF', '876'); -- 'Wallis and Futuna'
INSERT INTO country (code, code_a3, code_num) VALUES ('EH', 'ESH', '732'); -- 'Western Sahara'
INSERT INTO country (code, code_a3, code_num) VALUES ('YE', 'YEM', '887'); -- 'Yemen'
INSERT INTO country (code, code_a3, code_num) VALUES ('ZM', 'ZMB', '894'); -- 'Zambia'
INSERT INTO country (code, code_a3, code_num) VALUES ('ZW', 'ZWE', '716'); -- 'Zimbabwe'
