INSERT INTO category_code (code_source, code, name) VALUES ('ota', '1', 'Airport');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '2', 'Amusement park');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '3', 'Aquarium');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '4', 'Auditorium');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '5', 'Beach');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '6', 'Boat dock');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '7', 'Bridge');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '8', 'Bus station');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '9', 'Business location');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '10', 'Canal');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '11', 'Car rental location');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '12', 'Casino');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '13', 'Cemetery');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '14', 'Church');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '15', 'Concert hall');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '16', 'Conference center');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '17', 'Convention center');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '18', 'Entertainment district');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '19', 'Factory');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '20', 'Fairground');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '21', 'Farm');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '22', 'Gallery');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '23', 'Historic building');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '24', 'Hospital');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '25', 'Lake');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '26', 'Landmark');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '27', 'Library');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '28', 'Marina');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '29', 'Market');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '30', 'Monument');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '31', 'Mountain');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '32', 'Museum');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '33', 'Ocean');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '34', 'Orchard');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '35', 'Palace');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '36', 'Park');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '37', 'Pier');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '38', 'Race track');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '39', 'Recreation center');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '40', 'Resort');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '41', 'Restaurant');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '42', 'River');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '43', 'School');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '44', 'Shopping mall');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '45', 'Ski area');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '46', 'Stadium');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '47', 'Store');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '48', 'Studio');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '49', 'Subway station');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '50', 'Theater/cinema');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '51', 'Train station');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '52', 'Trolley station');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '53', 'University');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '54', 'Water park');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '55', 'Waterfront');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '56', 'Winery');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '57', 'Zoo');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '58', 'City event');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '59', 'Festival');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '60', 'Tournament');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '61', 'Tour');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '62', 'Other');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '63', 'College');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '64', 'Nightlife');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '65', 'Shopping');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '66', 'Sports');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '67', 'City center');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '68', 'City downtown');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '69', 'Local company');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '70', 'Cruise port');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '71', 'Live theatre');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '72', 'Arena');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '73', 'Bar');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '74', 'Bay');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '75', 'Cathedral');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '76', 'Corporate offices');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '77', 'Educational institution');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '78', 'Financial district');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '79', 'Financial institution');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '80', 'Medical facility');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '81', 'Mosque');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '82', 'Synagogue');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '83', 'Suburb');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '84', 'Army base');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '85', 'Commercial district');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '86', 'Tourist site');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '87', 'Miscellaneous');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '88', 'Agricultural');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '89', 'Archeological');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '90', 'Botanical garden');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '91', 'Bowling');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '92', 'Cultural center');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '93', 'Equestrian center');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '94', 'Handicraft center');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '95', 'Natural attraction');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '96', 'Performing art center');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '97', 'Planetarium/science center');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '98', 'Cable cars');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '99', 'Company');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '100', 'Factory/business tour');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '101', 'Nighttime entertainment');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '102', 'Local bus stop');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '103', 'Convention and visitors bureau');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '104', 'Art');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '105', 'Music');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '106', 'State/national Park');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '107', 'Exhibition/conference center');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '108', 'Non-comercial airport');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '109', 'Naval base');
INSERT INTO category_code (code_source, code, name) VALUES ('ota', '110', 'Military base');
