INSERT INTO brand (name) VALUES ('25 Hours');
INSERT INTO brand (name) VALUES ('7 days');
INSERT INTO brand (name) VALUES ('AC Hotels');
INSERT INTO brand (name) VALUES ('Adagio');
INSERT INTO brand (name) VALUES ('Aiden');
INSERT INTO brand (name) VALUES ('Aloft Hotels');
INSERT INTO brand (name) VALUES ('Aman');
INSERT INTO brand (name) VALUES ('Amari Hotels and Resorts');
INSERT INTO brand (name) VALUES ('Americas Best Value Inn');
INSERT INTO brand (name) VALUES ('AmericInn');
INSERT INTO brand (name) VALUES ('Ananda');
INSERT INTO brand (name) VALUES ('Anantara');
INSERT INTO brand (name) VALUES ('Andaz');
INSERT INTO brand (name) VALUES ('Angsana');
INSERT INTO brand (name) VALUES ('Angsana');
INSERT INTO brand (name) VALUES ('APA Hotels');
INSERT INTO brand (name) VALUES ('Apartments by Ligula');
INSERT INTO brand (name) VALUES ('Art Series');
INSERT INTO brand (name) VALUES ('ASAI HOTELS');
INSERT INTO brand (name) VALUES ('Ascend Collection');
INSERT INTO brand (name) VALUES ('Ascott The Residence');
INSERT INTO brand (name) VALUES ('Atwell Suites');
INSERT INTO brand (name) VALUES ('Autograph Collection');
INSERT INTO brand (name) VALUES ('Avari hotels');
INSERT INTO brand (name) VALUES ('Avid Hotels');
INSERT INTO brand (name) VALUES ('Banyan Tree');
INSERT INTO brand (name) VALUES ('Baymont');
INSERT INTO brand (name) VALUES ('Belmond');
INSERT INTO brand (name) VALUES ('Best Western');
INSERT INTO brand (name) VALUES ('Best Western Plus');
INSERT INTO brand (name) VALUES ('Best Western Premier');
INSERT INTO brand (name) VALUES ('Breakfree');
INSERT INTO brand (name) VALUES ('Brown');
INSERT INTO brand (name) VALUES ('Bulgari Hotels');
INSERT INTO brand (name) VALUES ('BW Premier Collection');
INSERT INTO brand (name) VALUES ('BW Signature Collection by Best Western');
INSERT INTO brand (name) VALUES ('Cambria Suites');
INSERT INTO brand (name) VALUES ('Campanile');
INSERT INTO brand (name) VALUES ('Canadas Best Value Inn');
INSERT INTO brand (name) VALUES ('Candlewood Suites');
INSERT INTO brand (name) VALUES ('Canopy by Hilton');
INSERT INTO brand (name) VALUES ('Capital O');
INSERT INTO brand (name) VALUES ('Cassia');
INSERT INTO brand (name) VALUES ('Centara');
INSERT INTO brand (name) VALUES ('Centara Boutique Collection');
INSERT INTO brand (name) VALUES ('Centara Grand');
INSERT INTO brand (name) VALUES ('Centara Reserve');
INSERT INTO brand (name) VALUES ('Centara Residences & Suites');
INSERT INTO brand (name) VALUES ('Centra by Centara');
INSERT INTO brand (name) VALUES ('Chedi Hotels');
INSERT INTO brand (name) VALUES ('Cinnaomon Hotels and Resorts');
INSERT INTO brand (name) VALUES ('Citadines Apart''hotel');
INSERT INTO brand (name) VALUES ('Citin Hotel');
INSERT INTO brand (name) VALUES ('Citrus Hotel');
INSERT INTO brand (name) VALUES ('Clarion Collection');
INSERT INTO brand (name) VALUES ('Clarion Hotel');
INSERT INTO brand (name) VALUES ('Clarion Hotels');
INSERT INTO brand (name) VALUES ('Clarion Inn');
INSERT INTO brand (name) VALUES ('Clayton');
INSERT INTO brand (name) VALUES ('Coast Hotels');
INSERT INTO brand (name) VALUES ('Collection by Ligula');
INSERT INTO brand (name) VALUES ('Collection O');
INSERT INTO brand (name) VALUES ('Comfort Inn');
INSERT INTO brand (name) VALUES ('Comfort Suites');
INSERT INTO brand (name) VALUES ('Compass');
INSERT INTO brand (name) VALUES ('Conrad Hotels');
INSERT INTO brand (name) VALUES ('Copthorne Hotels');
INSERT INTO brand (name) VALUES ('Cordis Hotels');
INSERT INTO brand (name) VALUES ('COSI');
INSERT INTO brand (name) VALUES ('Country Hearth Inn & Suites');
INSERT INTO brand (name) VALUES ('Country Inn & Suites');
INSERT INTO brand (name) VALUES ('Courtyard by Marriott');
INSERT INTO brand (name) VALUES ('Crowne Plaza');
INSERT INTO brand (name) VALUES ('Curio Collection');
INSERT INTO brand (name) VALUES ('Days Inn');
INSERT INTO brand (name) VALUES ('Dazzler');
INSERT INTO brand (name) VALUES ('Delano');
INSERT INTO brand (name) VALUES ('Delta');
INSERT INTO brand (name) VALUES ('Design Hotels');
INSERT INTO brand (name) VALUES ('Dhawa');
INSERT INTO brand (name) VALUES ('Dolce');
INSERT INTO brand (name) VALUES ('Dorchester Collection');
INSERT INTO brand (name) VALUES ('DoubleTree');
INSERT INTO brand (name) VALUES ('Drury Inn');
INSERT INTO brand (name) VALUES ('Drury Inn and Suites');
INSERT INTO brand (name) VALUES ('Drury Plaza Hotel');
INSERT INTO brand (name) VALUES ('Drury Suites');
INSERT INTO brand (name) VALUES ('Dusit Devarana');
INSERT INTO brand (name) VALUES ('Dusit Princess');
INSERT INTO brand (name) VALUES ('Dusit Residence');
INSERT INTO brand (name) VALUES ('Dusit Thani');
INSERT INTO brand (name) VALUES ('dusitD2');
INSERT INTO brand (name) VALUES ('Eaton HotelsChelsea Hotels');
INSERT INTO brand (name) VALUES ('Econo Lodge');
INSERT INTO brand (name) VALUES ('Edition Hotels');
INSERT INTO brand (name) VALUES ('Elan Hotel');
INSERT INTO brand (name) VALUES ('Element Hotels');
INSERT INTO brand (name) VALUES ('Elewana');
INSERT INTO brand (name) VALUES ('Elite Hotel');
INSERT INTO brand (name) VALUES ('Embassy Suites Hotels');
INSERT INTO brand (name) VALUES ('Esplendor');
INSERT INTO brand (name) VALUES ('Estudio 6');
INSERT INTO brand (name) VALUES ('EVEN Hotels');
INSERT INTO brand (name) VALUES ('Excel');
INSERT INTO brand (name) VALUES ('Executive Residency by Best Western');
INSERT INTO brand (name) VALUES ('Extended Stay America');
INSERT INTO brand (name) VALUES ('Fairfield Inn by Marriott');
INSERT INTO brand (name) VALUES ('Fairmont');
INSERT INTO brand (name) VALUES ('Fairyland Hotels');
INSERT INTO brand (name) VALUES ('First Hotels');
INSERT INTO brand (name) VALUES ('Four Points by Sheraton');
INSERT INTO brand (name) VALUES ('Four Seasons Hotels');
INSERT INTO brand (name) VALUES ('Gaylord Hotels');
INSERT INTO brand (name) VALUES ('Ginger Hotels');
INSERT INTO brand (name) VALUES ('Glo');
INSERT INTO brand (name) VALUES ('Good Morning Hotels');
INSERT INTO brand (name) VALUES ('Gran Meliá');
INSERT INTO brand (name) VALUES ('Grand Copthrone Hotels');
INSERT INTO brand (name) VALUES ('Grand Hyatt');
INSERT INTO brand (name) VALUES ('Grand Mercure');
INSERT INTO brand (name) VALUES ('Grand Millenium Hotels');
INSERT INTO brand (name) VALUES ('Grand Prince');
INSERT INTO brand (name) VALUES ('GreenTree Eastern');
INSERT INTO brand (name) VALUES ('GreenTree Inn');
INSERT INTO brand (name) VALUES ('GTA Hotel');
INSERT INTO brand (name) VALUES ('GuestHouse');
INSERT INTO brand (name) VALUES ('Hampton by Hilton');
INSERT INTO brand (name) VALUES ('HanTing Hotel');
INSERT INTO brand (name) VALUES ('HanTing Plus Hotel');
INSERT INTO brand (name) VALUES ('Hawthorn Suites');
INSERT INTO brand (name) VALUES ('Hesperia Resorts');
INSERT INTO brand (name) VALUES ('Hi Inn');
INSERT INTO brand (name) VALUES ('Hilton Garden Inn');
INSERT INTO brand (name) VALUES ('Hilton Hotels & Resorts');
INSERT INTO brand (name) VALUES ('Holiday Inn');
INSERT INTO brand (name) VALUES ('Holiday Inn Express');
INSERT INTO brand (name) VALUES ('Holiday Inn Select');
INSERT INTO brand (name) VALUES ('Home Inns');
INSERT INTO brand (name) VALUES ('Home2 Suites');
INSERT INTO brand (name) VALUES ('Homeinn Plus');
INSERT INTO brand (name) VALUES ('HomeTowne Studios by Red Roof');
INSERT INTO brand (name) VALUES ('Homewood Suites by Hilton');
INSERT INTO brand (name) VALUES ('Hoshinoya');
INSERT INTO brand (name) VALUES ('Hotel 6');
INSERT INTO brand (name) VALUES ('Hotel Indigo');
INSERT INTO brand (name) VALUES ('Hotel JAL City');
INSERT INTO brand (name) VALUES ('Hotel Jen');
INSERT INTO brand (name) VALUES ('Hotel RL');
INSERT INTO brand (name) VALUES ('hotelF1');
INSERT INTO brand (name) VALUES ('Howard Johnson''s');
INSERT INTO brand (name) VALUES ('HUALUXE Hotels & Resorts');
INSERT INTO brand (name) VALUES ('hub by Premier Inn');
INSERT INTO brand (name) VALUES ('Hyatt Centric');
INSERT INTO brand (name) VALUES ('Hyatt Hotels');
INSERT INTO brand (name) VALUES ('Hyatt House Hotels');
INSERT INTO brand (name) VALUES ('Hyatt Place');
INSERT INTO brand (name) VALUES ('Hyatt Regency');
INSERT INTO brand (name) VALUES ('Hyde');
INSERT INTO brand (name) VALUES ('ibis');
INSERT INTO brand (name) VALUES ('ibis budget');
INSERT INTO brand (name) VALUES ('ibis Styles');
INSERT INTO brand (name) VALUES ('Innside');
INSERT INTO brand (name) VALUES ('InterContinental');
INSERT INTO brand (name) VALUES ('InTown Suites');
INSERT INTO brand (name) VALUES ('J');
INSERT INTO brand (name) VALUES ('Jetwing Hotels');
INSERT INTO brand (name) VALUES ('JI Hotel');
INSERT INTO brand (name) VALUES ('Jinjiang');
INSERT INTO brand (name) VALUES ('Jinjiang Inns');
INSERT INTO brand (name) VALUES ('Jinjiang Metropolis');
INSERT INTO brand (name) VALUES ('Jo&Joe');
INSERT INTO brand (name) VALUES ('Joya Hotel');
INSERT INTO brand (name) VALUES ('Jumeirah');
INSERT INTO brand (name) VALUES ('JW Marriott Hotels');
INSERT INTO brand (name) VALUES ('Kai');
INSERT INTO brand (name) VALUES ('Kempinski');
INSERT INTO brand (name) VALUES ('Kerry Hotels');
INSERT INTO brand (name) VALUES ('KHOS');
INSERT INTO brand (name) VALUES ('Kimpton Hotels & Restaurants');
INSERT INTO brand (name) VALUES ('Kingsgate Hotels');
INSERT INTO brand (name) VALUES ('Kunlun');
INSERT INTO brand (name) VALUES ('L7 hotels');
INSERT INTO brand (name) VALUES ('La Quinta');
INSERT INTO brand (name) VALUES ('Langham Hotels');
INSERT INTO brand (name) VALUES ('Langham Place Hotels');
INSERT INTO brand (name) VALUES ('Le Fouquet''s Paris');
INSERT INTO brand (name) VALUES ('Le Majestic Cannes');
INSERT INTO brand (name) VALUES ('Le Méridien');
INSERT INTO brand (name) VALUES ('Le Normandy Deauville');
INSERT INTO brand (name) VALUES ('Les Neiges Courchevel');
INSERT INTO brand (name) VALUES ('Li Feng');
INSERT INTO brand (name) VALUES ('Lifestyle Holidays Hotels and Resorts');
INSERT INTO brand (name) VALUES ('Loews Hotels');
INSERT INTO brand (name) VALUES ('Lotte City Hotels');
INSERT INTO brand (name) VALUES ('Lotte Hotels');
INSERT INTO brand (name) VALUES ('Lotte Resorts');
INSERT INTO brand (name) VALUES ('Luxury Collection');
INSERT INTO brand (name) VALUES ('lyf');
INSERT INTO brand (name) VALUES ('M Hotels');
INSERT INTO brand (name) VALUES ('Magnuson Grand');
INSERT INTO brand (name) VALUES ('Magnuson Hotels');
INSERT INTO brand (name) VALUES ('Mainstay Suites');
INSERT INTO brand (name) VALUES ('Maldron');
INSERT INTO brand (name) VALUES ('Mama Shelter');
INSERT INTO brand (name) VALUES ('Mandarin Oriental');
INSERT INTO brand (name) VALUES ('Mantis');
INSERT INTO brand (name) VALUES ('Mantra');
INSERT INTO brand (name) VALUES ('Manxin Hotels & Resorts');
INSERT INTO brand (name) VALUES ('Marriott');
INSERT INTO brand (name) VALUES ('Marriott Executive Apartment');
INSERT INTO brand (name) VALUES ('ME by Meliá');
INSERT INTO brand (name) VALUES ('Meliá');
INSERT INTO brand (name) VALUES ('Mercure');
INSERT INTO brand (name) VALUES ('MGallery');
INSERT INTO brand (name) VALUES ('Microtel');
INSERT INTO brand (name) VALUES ('Millennium Hotels');
INSERT INTO brand (name) VALUES ('Mondrian');
INSERT INTO brand (name) VALUES ('Motel 168');
INSERT INTO brand (name) VALUES ('Motel 6');
INSERT INTO brand (name) VALUES ('Motel L');
INSERT INTO brand (name) VALUES ('Motto by Hilton');
INSERT INTO brand (name) VALUES ('Mövenpick');
INSERT INTO brand (name) VALUES ('MOXY Hotels');
INSERT INTO brand (name) VALUES ('M-Star Hotels');
INSERT INTO brand (name) VALUES ('New World Hotels');
INSERT INTO brand (name) VALUES ('NH Collection');
INSERT INTO brand (name) VALUES ('NH Hoteles');
INSERT INTO brand (name) VALUES ('NHow');
INSERT INTO brand (name) VALUES ('Nikko Hotels');
INSERT INTO brand (name) VALUES ('Nordic Choice Hotels & Resorts');
INSERT INTO brand (name) VALUES ('Novotel');
INSERT INTO brand (name) VALUES ('Oaks Hotels & Resorts');
INSERT INTO brand (name) VALUES ('Oberoi Hotels');
INSERT INTO brand (name) VALUES ('Okura Hotels & Resorts');
INSERT INTO brand (name) VALUES ('Omni Hotels & Resorts');
INSERT INTO brand (name) VALUES ('OMO');
INSERT INTO brand (name) VALUES ('onefinestay');
INSERT INTO brand (name) VALUES ('Orange Hotel');
INSERT INTO brand (name) VALUES ('Orange Selected');
INSERT INTO brand (name) VALUES ('Orient Express');
INSERT INTO brand (name) VALUES ('Oriental Residence');
INSERT INTO brand (name) VALUES ('OYO Home');
INSERT INTO brand (name) VALUES ('OYO Hotel & Casino');
INSERT INTO brand (name) VALUES ('OYO Life');
INSERT INTO brand (name) VALUES ('OYO Rooms');
INSERT INTO brand (name) VALUES ('OYO Townhouse');
INSERT INTO brand (name) VALUES ('OYO Vacation Homes');
INSERT INTO brand (name) VALUES ('OZO');
INSERT INTO brand (name) VALUES ('Palette Resort');
INSERT INTO brand (name) VALUES ('Pan Pacific');
INSERT INTO brand (name) VALUES ('Paradisus');
INSERT INTO brand (name) VALUES ('Park Hyatt');
INSERT INTO brand (name) VALUES ('Park Inn by Radisson');
INSERT INTO brand (name) VALUES ('Park Plaza');
INSERT INTO brand (name) VALUES ('PARKROYAL');
INSERT INTO brand (name) VALUES ('PARKROYAL COLLECTION');
INSERT INTO brand (name) VALUES ('Pear Tree Inn');
INSERT INTO brand (name) VALUES ('Pentahotels');
INSERT INTO brand (name) VALUES ('Peppers');
INSERT INTO brand (name) VALUES ('Per Aquum');
INSERT INTO brand (name) VALUES ('Premier Inn');
INSERT INTO brand (name) VALUES ('Prince');
INSERT INTO brand (name) VALUES ('prizeotel');
INSERT INTO brand (name) VALUES ('Profil Hotels');
INSERT INTO brand (name) VALUES ('Protea Hotels');
INSERT INTO brand (name) VALUES ('Pullman');
INSERT INTO brand (name) VALUES ('Quality Inn');
INSERT INTO brand (name) VALUES ('Quest Apartment Hotels');
INSERT INTO brand (name) VALUES ('Radisson');
INSERT INTO brand (name) VALUES ('Radisson Blu');
INSERT INTO brand (name) VALUES ('Radisson Collection');
INSERT INTO brand (name) VALUES ('Radisson Red');
INSERT INTO brand (name) VALUES ('Raffles');
INSERT INTO brand (name) VALUES ('Ramada');
INSERT INTO brand (name) VALUES ('Red Lion Hotels');
INSERT INTO brand (name) VALUES ('Red Lion Inn & Suites');
INSERT INTO brand (name) VALUES ('Red Planet');
INSERT INTO brand (name) VALUES ('Red Roof Inn');
INSERT INTO brand (name) VALUES ('Red Roof PLUS+');
INSERT INTO brand (name) VALUES ('Regent Hotels & Resorts');
INSERT INTO brand (name) VALUES ('REI');
INSERT INTO brand (name) VALUES ('Renaissance Hotels');
INSERT INTO brand (name) VALUES ('Residence Inn by Marriott');
INSERT INTO brand (name) VALUES ('Risonare');
INSERT INTO brand (name) VALUES ('Ritz-Carlton');
INSERT INTO brand (name) VALUES ('RIU Holiday');
INSERT INTO brand (name) VALUES ('RIU Plaza');
INSERT INTO brand (name) VALUES ('Rixos');
INSERT INTO brand (name) VALUES ('Rock Garden');
INSERT INTO brand (name) VALUES ('Rodeway Inn');
INSERT INTO brand (name) VALUES ('Rosewood Hotels & Resorts');
INSERT INTO brand (name) VALUES ('Sadie');
INSERT INTO brand (name) VALUES ('Saffron');
INSERT INTO brand (name) VALUES ('SAii');
INSERT INTO brand (name) VALUES ('Santiburi');
INSERT INTO brand (name) VALUES ('Scandic');
INSERT INTO brand (name) VALUES ('Settle Inn Extended Stay');
INSERT INTO brand (name) VALUES ('Shahpura Hotels');
INSERT INTO brand (name) VALUES ('Shama');
INSERT INTO brand (name) VALUES ('Shama Hub');
INSERT INTO brand (name) VALUES ('Shangri-La Hotels');
INSERT INTO brand (name) VALUES ('Shell Hotel');
INSERT INTO brand (name) VALUES ('Sheraton');
INSERT INTO brand (name) VALUES ('Shilo Inns');
INSERT INTO brand (name) VALUES ('Signature Inn');
INSERT INTO brand (name) VALUES ('Signiel');
INSERT INTO brand (name) VALUES ('Sleep Inn');
INSERT INTO brand (name) VALUES ('SLS');
INSERT INTO brand (name) VALUES ('SO/');
INSERT INTO brand (name) VALUES ('Sofitel');
INSERT INTO brand (name) VALUES ('Sofitel Legend');
INSERT INTO brand (name) VALUES ('Sol');
INSERT INTO brand (name) VALUES ('Somerset Serviced Residence');
INSERT INTO brand (name) VALUES ('Sonava FushiSoneva Jani');
INSERT INTO brand (name) VALUES ('Soneva Kiri');
INSERT INTO brand (name) VALUES ('Spot On');
INSERT INTO brand (name) VALUES ('SpringHill Suites');
INSERT INTO brand (name) VALUES ('St. Regis');
INSERT INTO brand (name) VALUES ('Starway Hotel');
INSERT INTO brand (name) VALUES ('Staybridge Suites');
INSERT INTO brand (name) VALUES ('Studio 6');
INSERT INTO brand (name) VALUES ('Suburban Extended Stay Hotel');
INSERT INTO brand (name) VALUES ('Super 8');
INSERT INTO brand (name) VALUES ('SureStay Collection by Best Western');
INSERT INTO brand (name) VALUES ('SureStay Hotel by Best Western');
INSERT INTO brand (name) VALUES ('SureStay Plus Hotel by Best Western');
INSERT INTO brand (name) VALUES ('Swissôtel');
INSERT INTO brand (name) VALUES ('Taj Exotica');
INSERT INTO brand (name) VALUES ('Taj Hotels');
INSERT INTO brand (name) VALUES ('The Crest Collection');
INSERT INTO brand (name) VALUES ('The Gateway Hotels');
INSERT INTO brand (name) VALUES ('The House of Originals');
INSERT INTO brand (name) VALUES ('The Mosaic Collection');
INSERT INTO brand (name) VALUES ('The Okura Prestige');
INSERT INTO brand (name) VALUES ('The Peninsula Hotels');
INSERT INTO brand (name) VALUES ('The Prince');
INSERT INTO brand (name) VALUES ('The Red Collection');
INSERT INTO brand (name) VALUES ('The Sebel');
INSERT INTO brand (name) VALUES ('Tivoli');
INSERT INTO brand (name) VALUES ('Tokyu');
INSERT INTO brand (name) VALUES ('TownePlace Suites');
INSERT INTO brand (name) VALUES ('Trademark');
INSERT INTO brand (name) VALUES ('Traders Hotels');
INSERT INTO brand (name) VALUES ('Travelodge');
INSERT INTO brand (name) VALUES ('Tribe');
INSERT INTO brand (name) VALUES ('Tribute Portfolio');
INSERT INTO brand (name) VALUES ('Trident Hotels');
INSERT INTO brand (name) VALUES ('Tru by Hilton');
INSERT INTO brand (name) VALUES ('TRYP');
INSERT INTO brand (name) VALUES ('Tulip Golden Tulip');
INSERT INTO brand (name) VALUES ('Vacation Rentals by Nordic Choice Hotels');
INSERT INTO brand (name) VALUES ('Vatica Hotel');
INSERT INTO brand (name) VALUES ('Vib');
INSERT INTO brand (name) VALUES ('Vienna');
INSERT INTO brand (name) VALUES ('Vivanta by Taj');
INSERT INTO brand (name) VALUES ('W Hotels');
INSERT INTO brand (name) VALUES ('Waldorf Astoria');
INSERT INTO brand (name) VALUES ('Westin Hotels & Resorts');
INSERT INTO brand (name) VALUES ('Wingate');
INSERT INTO brand (name) VALUES ('WoodSpring Suites');
INSERT INTO brand (name) VALUES ('Wyndham');
INSERT INTO brand (name) VALUES ('Wyndham Garden');
INSERT INTO brand (name) VALUES ('Wyndham Grand');
INSERT INTO brand (name) VALUES ('Yitel');
INSERT INTO brand (name) VALUES ('Yoo Collection');
INSERT INTO brand (name) VALUES ('YOO2');
INSERT INTO brand (name) VALUES ('Zhe');
