-- OTA (PCT) Property Class Type Codes
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('1', 'All suite', 'ota', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('2', 'All-Inclusive resort', 'ota', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('3', 'Apartment', 'ota', 'Apartment');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('4', 'Bed and breakfast', 'ota', 'Apartment');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('5', 'Cabin or bungalow', 'ota', 'Holiday Home');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('6', 'Campground', 'ota', 'Camping');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('7', 'Chalet', 'ota', 'Chalet');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('8', 'Condominium', 'ota', 'Holiday Home');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('9', 'Conference center', 'ota', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('10', 'Corporate', 'ota', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('11', 'Corporate business transient', 'ota', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('12', 'Cruise', 'ota', 'Boat');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('13', 'Extended stay', 'ota', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('14', 'Ferry', 'ota', 'Boat');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('15', 'Guest farm', 'ota', 'Farm stay');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('16', 'Guest house limited service', 'ota', 'Guest House');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('17', 'Health spa', 'ota', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('18', 'Holiday resort', 'ota', 'Resort');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('19', 'Hostel', 'ota', 'Hostel');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('20', 'Hotel', 'ota', 'Hotel');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('21', 'Inn', 'ota', 'Inn');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('22', 'Lodge', 'ota', 'Lodge');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('23', 'Meeting resort', 'ota', 'Resort');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('24', 'Meeting/Convention', 'ota', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('25', 'Mobile-home', 'ota', 'Holiday Home');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('26', 'Monastery', 'ota', 'Homestay');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('27', 'Motel', 'ota', 'Motel');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('28', 'Ranch', 'ota', 'Farm stay');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('29', 'Residential apartment', 'ota', 'Apartment');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('30', 'Resort', 'ota', 'Resort');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('31', 'Sailing ship', 'ota', 'Boat');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('32', 'Self catering accommodation', 'ota', 'Apartment');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('33', 'Tent', 'ota', 'Tented');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('34', 'Vacation home', 'ota', 'Holiday Home');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('35', 'Villa', 'ota', 'Villa');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('36', 'Wildlife reserve', 'ota', 'Resort');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('37', 'Castle', 'ota', 'Holiday Home');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('38', 'Convention Network Property', 'ota', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('39', 'Golf', 'ota', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('40', 'Pension', 'ota', 'Guest House');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('41', 'Ski', 'ota', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('42', 'Spa', 'ota', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('43', 'Time share', 'ota', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('44', 'Boatel', 'ota', 'Boat');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('45', 'Boutique', 'ota', 'Hotel');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('46', 'Efficiency/studio', 'ota', 'Apartment');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('47', 'Full service', 'ota', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('48', 'Historical', 'ota', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('49', 'Limited service', 'ota', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('50', 'Recreational vehicle park', 'ota', 'Camping');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('51', 'Charm hotel', 'ota', 'Hotel');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('52', 'Manor', 'ota', 'Holiday Home');
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('53', 'Vacation rental', 'ota', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('54', 'Economy', 'ota', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('55', 'Midscale', 'ota', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('56', 'Upscale', 'ota', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('57', 'Luxury', 'ota', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('58', 'Union', 'ota', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('59', 'Leisure', 'ota', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('60', 'Wholesale', 'ota', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('61', 'Transient', 'ota', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('62', 'Other', 'ota', null);


-- Booking.com extended
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('5000', 'ApartHotel', 'booking', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('5001', 'Riad', 'booking', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('5002', 'Ryokan', 'booking', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('5003', 'Love Hotel', 'booking', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('5004', 'Homestay', 'booking', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('5005', 'Japanese-style Business Hotel', 'booking', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('5006', 'Holiday Home', 'booking', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('5007', 'Country house', 'booking', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('5008', 'Capsule Hotel', 'booking', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('5009', 'Holiday Park', 'booking', null);


-- Internal
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('1001', 'Hut', 'cultswitch', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('1002', 'Not specified', 'cultswitch', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('1003', 'Youth Guest House', 'cultswitch', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('1004', 'Youth Hostel', 'cultswitch', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('1005', 'Huts_Hotel', 'cultswitch', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('1006', 'Private_Home', 'cultswitch', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('1007', 'Private_Room', 'cultswitch', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('1008', 'Beach hotel', 'cultswitch', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('1009', 'Winter sports hotel', 'cultswitch', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('1010', 'Luxury hotel', 'cultswitch', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('1011', 'Design hotel', 'cultswitch', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('1012', 'Small, intimate, quiet hotel', 'cultswitch', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('1013', 'Family hotel', 'cultswitch', null);
INSERT INTO property_type (code, name, code_source, alternative_name) VALUES ('1014', 'Handicapped accessible hotel', 'cultswitch', null);
