UPDATE brand SET code = '25hours' WHERE name = '25 Hours';
UPDATE brand SET code = 'AR' WHERE name = 'AC Hotels';
UPDATE brand SET code = 'AA' WHERE name = 'AmericInn';
UPDATE brand SET code = 'NZ' WHERE name = 'Ascend Collection';
UPDATE brand SET code = 'BY' WHERE name = 'Banyan Tree';
UPDATE brand SET code = 'BG' WHERE name = 'Bulgari Hotels';
UPDATE brand SET code = 'EZ' WHERE name = 'Cambria Suites';
UPDATE brand SET code = 'YO' WHERE name = 'Candlewood Suites';
UPDATE brand SET code = 'PY' WHERE name = 'Canopy by Hilton';
UPDATE brand SET code = 'WX' WHERE name = 'Coast Hotels';
UPDATE brand SET code = 'CI' WHERE name = 'Comfort Inn';
UPDATE brand SET code = 'CZ' WHERE name = 'Comfort Suites';
UPDATE brand SET code = 'CHI' WHERE name = 'Country Inn & Suites';
UPDATE brand SET code = 'CY' WHERE name = 'Courtyard by Marriott';
UPDATE brand SET code = 'DI' WHERE name = 'Days Inn';
UPDATE brand SET code = 'DS' WHERE name = 'Design Hotels';
UPDATE brand SET name = 'Eaton Hotels' WHERE name = 'Eaton HotelsChelsea Hotels';
UPDATE brand SET code = 'EQ' WHERE name = 'Eaton Hotels';
UPDATE brand SET code = 'EL' WHERE name = 'Element Hotels';
UPDATE brand SET code = 'EO' WHERE name = 'Econo Lodge';
UPDATE brand SET code = 'ES' WHERE name = 'Embassy Suites Hotels';
UPDATE brand SET code = 'VN' WHERE name = 'EVEN Hotels';
UPDATE brand SET code = 'EA' WHERE name = 'Extended Stay America';
UPDATE brand SET code = 'FN' WHERE name = 'Fairfield Inn by Marriott';
UPDATE brand SET code = 'FX' WHERE name = 'First Hotels';
UPDATE brand SET code = 'FP' WHERE name = 'Four Points by Sheraton';
UPDATE brand SET code = 'FS' WHERE name = 'Four Seasons Hotels';
UPDATE brand SET code = 'MJ' WHERE name = 'Grand Mercure';
UPDATE brand SET code = 'BH' WHERE name = 'Hawthorn Suites';
UPDATE brand SET code = 'GI' WHERE name = 'Hilton Garden Inn';
UPDATE brand SET code = 'EX' WHERE name = 'Holiday Inn Express';
UPDATE brand SET code = 'HZ' WHERE name = 'Hyatt Place';
UPDATE brand SET code = 'IB' WHERE name = 'ibis budget';
UPDATE brand SET code = 'IE' WHERE name = 'ibis Styles';
UPDATE brand SET code = 'JT' WHERE name = 'Jumeirah';
UPDATE brand SET code = 'KH' WHERE name = 'Kerry Hotels';
UPDATE brand SET code = 'LQ' WHERE name = 'La Quinta';
UPDATE brand SET code = 'LO' WHERE name = 'Langham Hotels';
UPDATE brand SET code = 'LZ' WHERE name = 'Loews Hotels';
UPDATE brand SET code = 'OX' WHERE name = 'MOXY Hotels';
UPDATE brand SET code = 'MZ' WHERE name = 'Mainstay Suites';
UPDATE brand SET code = 'EB' WHERE name = 'Marriott';
UPDATE brand SET code = 'MX' WHERE name = 'Motel 6';
UPDATE brand SET code = 'AP' WHERE name = 'NH Hoteles';
UPDATE brand SET code = 'NF' WHERE name = 'Novotel';
UPDATE brand SET code = 'NW' WHERE name = 'New World Hotels';
UPDATE brand SET code = 'OB' WHERE name = 'Oberoi Hotels';
UPDATE brand SET code = 'OC' WHERE name = 'Okura Hotels & Resorts';
UPDATE brand SET code = 'PKP' WHERE name = 'Park Plaza';
UPDATE brand SET code = 'PR' WHERE name = 'PARKROYAL';
UPDATE brand SET code = 'P2' WHERE name = 'Protea Hotels';
UPDATE brand SET code = 'PU' WHERE name = 'Pullman';
UPDATE brand SET code = 'QI' WHERE name = 'Quality Inn';
UPDATE brand SET code = 'RF' WHERE name = 'Red Roof Inn';
UPDATE brand SET code = 'RC' WHERE name = 'Residence Inn by Marriott';
UPDATE brand SET code = 'R0' WHERE name = 'Rixos';
UPDATE brand SET code = 'RI' WHERE name = 'Rodeway Inn';
UPDATE brand SET code = 'RW' WHERE name = 'Rosewood Hotels & Resorts';
UPDATE brand SET code = 'SZ' WHERE name = 'Sleep Inn';
UPDATE brand SET code = 'S8' WHERE name = 'Sofitel Legend';
UPDATE brand SET code = 'XV' WHERE name = 'SpringHill Suites';
UPDATE brand SET code = 'XR' WHERE name = 'St. Regis';
UPDATE brand SET code = 'SS' WHERE name = 'Studio 6';
UPDATE brand SET code = 'SL' WHERE name = 'Swissôtel';
UPDATE brand SET code = 'LC' WHERE name = 'Luxury Collection';
UPDATE brand SET code = 'PN' WHERE name = 'The Peninsula Hotels';
UPDATE brand SET code = 'TB' WHERE name = 'The Sebel';
UPDATE brand SET code = 'TO' WHERE name = 'TownePlace Suites';
UPDATE brand SET code = 'TL' WHERE name = 'Travelodge';
UPDATE brand SET code = 'TX' WHERE name = 'Tribute Portfolio';
UPDATE brand SET code = 'TD' WHERE name = 'Trident Hotels';
UPDATE brand SET code = 'RU' WHERE name = 'Tru by Hilton';
UPDATE brand SET code = 'WH' WHERE name = 'W Hotels';
UPDATE brand SET code = 'WA' WHERE name = 'Waldorf Astoria';
UPDATE brand SET code = 'WI' WHERE name = 'Westin Hotels & Resorts';
UPDATE brand SET code = 'WS' WHERE name = 'WoodSpring Suites';
UPDATE brand SET code = 'PT' WHERE name = 'Pentahotels';


INSERT INTO brand (name) VALUES ('Chelsea Hotels');


INSERT INTO brand (name, code) VALUES ('ACCOR Hotels', 'XQ');
INSERT INTO brand (name, code) VALUES ('ADAGIO Access', 'AE');
INSERT INTO brand (name, code) VALUES ('AKZENT Hotels', 'akz');
INSERT INTO brand (name, code) VALUES ('ANA Hotels International', 'AN');
INSERT INTO brand (name, code) VALUES ('Abba Hoteles', 'AB');
INSERT INTO brand (name, code) VALUES ('Adagio City Aparthotel', 'AD');
INSERT INTO brand (name, code) VALUES ('Affinia Hospitality', 'NY');
INSERT INTO brand (name, code) VALUES ('Alesia Distribution', 'OK');
INSERT INTO brand (name, code) VALUES ('Alila Hotels', 'LF');
INSERT INTO brand (name, code) VALUES ('All Seasons Europe', 'AS');
INSERT INTO brand (name, code) VALUES ('All-Hotels', 'AL');
INSERT INTO brand (name, code) VALUES ('AltiusPar', 'YP');
INSERT INTO brand (name, code) VALUES ('Amadeus Hospitality', 'HC');
INSERT INTO brand (name, code) VALUES ('Andre Balazs Properties', 'BZ');
INSERT INTO brand (name, code) VALUES ('Aqua Hotels and Resorts', 'QU');
INSERT INTO brand (name, code) VALUES ('Aramark hotel', 'AF');
INSERT INTO brand (name, code) VALUES ('Archer Hotel', 'OA');
INSERT INTO brand (name, code) VALUES ('Armani Hotels', 'AI');
INSERT INTO brand (name, code) VALUES ('Art'' otel', 'AO');
INSERT INTO brand (name, code) VALUES ('Atel Hotels', 'AT');
INSERT INTO brand (name, code) VALUES ('B&B Hotels', 'bundb');
INSERT INTO brand (name, code) VALUES ('Baccarat and 1 Hotels', 'B2');
INSERT INTO brand (name, code) VALUES ('Barcelo Hotels', 'BN');
INSERT INTO brand (name, code) VALUES ('Baymont Inn & Suites', 'BU');
INSERT INTO brand (name, code) VALUES ('Benchmark Hotels', 'BM');
INSERT INTO brand (name, code) VALUES ('Best Value Inn and Suites', 'BV');
INSERT INTO brand (name, code) VALUES ('Best Western International', 'BW');
INSERT INTO brand (name, code) VALUES ('BlackPepper Hotels', 'CK');
INSERT INTO brand (name, code) VALUES ('Boscolo Hotels', 'BA');
INSERT INTO brand (name, code) VALUES ('Boutique', 'BC');
INSERT INTO brand (name, code) VALUES ('Boutique Desires Hotels', 'BT');
INSERT INTO brand (name, code) VALUES ('Brazil Hospitality Group', 'LT');
INSERT INTO brand (name, code) VALUES ('Brisas Hotels & Resorts', '000203');
INSERT INTO brand (name, code) VALUES ('COMO Hotels and Resorts', 'CV');
INSERT INTO brand (name, code) VALUES ('CORALIA CLUB - Accor vacances', 'XC');
INSERT INTO brand (name, code) VALUES ('Caesar Park Hotels & Resorts', 'CJ');
INSERT INTO brand (name, code) VALUES ('Camino Real Hotels & Resorts', 'CM');
INSERT INTO brand (name, code) VALUES ('Carino Hotels and Resorts', 'UN');
INSERT INTO brand (name, code) VALUES ('Catalonia Hoteles', 'cathot');
INSERT INTO brand (name, code) VALUES ('Chakela Hotels', 'C1');
INSERT INTO brand (name, code) VALUES ('Chateaux et Hotels Collection', 'C2');
INSERT INTO brand (name, code) VALUES ('City Express Hotels', 'XE');
INSERT INTO brand (name, code) VALUES ('City Partners Hotels', 'CF');
INSERT INTO brand (name, code) VALUES ('Clarion', 'CC');
INSERT INTO brand (name, code) VALUES ('Classic British Hotels', 'CB');
INSERT INTO brand (name, code) VALUES ('Classic International Hotels', 'IH');
INSERT INTO brand (name, code) VALUES ('Club Quarters', 'CQ');
INSERT INTO brand (name, code) VALUES ('ClubHouse Inn & Suites', 'KL');
INSERT INTO brand (name, code) VALUES ('Columbus Reservation Services', 'BX');
INSERT INTO brand (name, code) VALUES ('Concorde Hotels', 'CD');
INSERT INTO brand (name, code) VALUES ('Confortel Hotels', 'CA');
INSERT INTO brand (name, code) VALUES ('Conrad Hotels CN', 'CN');
INSERT INTO brand (name, code) VALUES ('Coral International', 'CE');
INSERT INTO brand (name, code) VALUES ('Corinthia Hotels and Resorts', 'IA');
INSERT INTO brand (name, code) VALUES ('Corus Hotels', 'CL');
INSERT INTO brand (name, code) VALUES ('Crowne Plaza Hotels and Resorts', 'CP');
INSERT INTO brand (name, code) VALUES ('Curio by Hilton', 'QQ');
INSERT INTO brand (name, code) VALUES ('De Vere Hotels', 'DV');
INSERT INTO brand (name, code) VALUES ('Delta Hotels', 'DE');
INSERT INTO brand (name, code) VALUES ('Destination Hotels & Resorts', 'DN');
INSERT INTO brand (name, code) VALUES ('Distinguished Hotels', 'DH');
INSERT INTO brand (name, code) VALUES ('Dolce International', 'DX');
INSERT INTO brand (name, code) VALUES ('Domina Hotels', 'DM');
INSERT INTO brand (name, code) VALUES ('Doral', 'DA');
INSERT INTO brand (name, code) VALUES ('Dorchester Group Hotels', 'DC');
INSERT INTO brand (name, code) VALUES ('Dorint Resorts', 'DO');
INSERT INTO brand (name, code) VALUES ('Doubletree Hotels', 'DT');
INSERT INTO brand (name, code) VALUES ('Dream Hotels', 'D2');
INSERT INTO brand (name, code) VALUES ('Drury Hotels', 'DR');
INSERT INTO brand (name, code) VALUES ('Dusit Hotels and Resorts', 'DW');
INSERT INTO brand (name, code) VALUES ('Eden Hotel Group', 'E2');
INSERT INTO brand (name, code) VALUES ('Edwardian Hotels', 'ED');
INSERT INTO brand (name, code) VALUES ('Envergure Hotels', 'NN');
INSERT INTO brand (name, code) VALUES ('Epoque Hotels', 'EP');
INSERT INTO brand (name, code) VALUES ('Eurostars Hotels', 'eusta');
INSERT INTO brand (name, code) VALUES ('Exclusive Hotels', 'EU');
INSERT INTO brand (name, code) VALUES ('Executive Hotels and Resorts', 'EI');
INSERT INTO brand (name, code) VALUES ('Fairmont Hotels', 'FA');
INSERT INTO brand (name, code) VALUES ('Falkensteiner Hotels and Residences', 'EK');
INSERT INTO brand (name, code) VALUES ('Far East Hospitality', 'EH');
INSERT INTO brand (name, code) VALUES ('Fastbooking', 'FG');
INSERT INTO brand (name, code) VALUES ('Fiesta Americana Hotels & Resorts', 'FH');
INSERT INTO brand (name, code) VALUES ('Flemings Hotels', 'flem');
INSERT INTO brand (name, code) VALUES ('Fontainebleau Resorts', 'FB');
INSERT INTO brand (name, code) VALUES ('Formule 1', 'F1');
INSERT INTO brand (name, code) VALUES ('Forte', 'FE');
INSERT INTO brand (name, code) VALUES ('Frasers Hospitality', 'FI');
INSERT INTO brand (name, code) VALUES ('Gansevoort Hotel Group', 'GV');
INSERT INTO brand (name, code) VALUES ('Gaylord Entertainment', 'GE');
INSERT INTO brand (name, code) VALUES ('GenaRes Worldwide Reservation Services', 'GZ');
INSERT INTO brand (name, code) VALUES ('Genre hotels', 'GQ');
INSERT INTO brand (name, code) VALUES ('GlobRes', 'GL');
INSERT INTO brand (name, code) VALUES ('Global Hotel Alliance', 'GA');
INSERT INTO brand (name, code) VALUES ('Golden Tulip', 'GT');
INSERT INTO brand (name, code) VALUES ('Gramercy Park Hotel', 'GN');
INSERT INTO brand (name, code) VALUES ('Grand City Hotels and Resorts', 'XF');
INSERT INTO brand (name, code) VALUES ('Grand Heritage Hotels', 'GH');
INSERT INTO brand (name, code) VALUES ('Grand Hospitality', 'GG');
INSERT INTO brand (name, code) VALUES ('Grand Pineapple Beach Resorts', 'PA');
INSERT INTO brand (name, code) VALUES ('Grand Tradition Hotels', 'GD');
INSERT INTO brand (name, code) VALUES ('Grandstay', 'GS');
INSERT INTO brand (name, code) VALUES ('Grange Hotels', 'GF');
INSERT INTO brand (name, code) VALUES ('Great Hotels of the World', 'GW');
INSERT INTO brand (name, code) VALUES ('GuestHouse International', 'GO');
INSERT INTO brand (name, code) VALUES ('H-Hotels', 'hhot');
INSERT INTO brand (name, code) VALUES ('Hampton Inn/Hampton Inn and Suites', 'HX');
INSERT INTO brand (name, code) VALUES ('Hard Rock Hotels', 'RK');
INSERT INTO brand (name, code) VALUES ('Hard Rock Hotels, Resorts and Casinos', 'DJ');
INSERT INTO brand (name, code) VALUES ('Harrahs Entertainment', 'HR');
INSERT INTO brand (name, code) VALUES ('Heikotels', 'Heikotel');
INSERT INTO brand (name, code) VALUES ('Hilton Hotels and Resorts(U. S.)', 'HH');
INSERT INTO brand (name, code) VALUES ('Hilton International', 'HL');
INSERT INTO brand (name, code) VALUES ('Historic  Hotels of America', 'HE');
INSERT INTO brand (name, code) VALUES ('Holiday Inn Hotels and Resorts', 'HI');
INSERT INTO brand (name, code) VALUES ('Home 2 Suites', 'HT');
INSERT INTO brand (name, code) VALUES ('Homewood Suites', 'HG');
INSERT INTO brand (name, code) VALUES ('HotelREZ', 'HO');
INSERT INTO brand (name, code) VALUES ('Hotels and Preference', 'IW');
INSERT INTO brand (name, code) VALUES ('Hotelwebservice', 'HF');
INSERT INTO brand (name, code) VALUES ('Hotusa Hotels', 'HA');
INSERT INTO brand (name, code) VALUES ('Howard Johnson Plazas, Hotels, Inns, and Express Inns', 'HJ');
INSERT INTO brand (name, code) VALUES ('Hualuxe Hotels', 'UL');
INSERT INTO brand (name, code) VALUES ('Husa Hoteles', 'husa');
INSERT INTO brand (name, code) VALUES ('Hyatt Hotels and Resorts', 'HY');
INSERT INTO brand (name, code) VALUES ('Hyatt Vacation Club', 'HU');
INSERT INTO brand (name, code) VALUES ('IBIS Hotels', 'XI');
INSERT INTO brand (name, code) VALUES ('Iberostar Hotels and Resorts', 'E5');
INSERT INTO brand (name, code) VALUES ('Independent Hotels', 'IM');
INSERT INTO brand (name, code) VALUES ('Indigo', 'IN');
INSERT INTO brand (name, code) VALUES ('Individualhotel', 'CLTZ');
INSERT INTO brand (name, code) VALUES ('InnFocus', 'IK');
INSERT INTO brand (name, code) VALUES ('InnPoints Reserv', 'IR');
INSERT INTO brand (name, code) VALUES ('InnVite', 'IV');
INSERT INTO brand (name, code) VALUES ('Inter-Continental Hotels and Resorts', 'IC');
INSERT INTO brand (name, code) VALUES ('InterCity Hotels', 'IT');
INSERT INTO brand (name, code) VALUES ('Interstate Hotels and Resorts', 'BK');
INSERT INTO brand (name, code) VALUES ('JG Black Book of Travel', 'JG');
INSERT INTO brand (name, code) VALUES ('JOYN Serviced Apartments', 'joyn');
INSERT INTO brand (name, code) VALUES ('JR Hotels', 'JR');
INSERT INTO brand (name, code) VALUES ('Jebel Ali International Hotels', 'JA');
INSERT INTO brand (name, code) VALUES ('Jin Jan', 'JJ');
INSERT INTO brand (name, code) VALUES ('Joie de Vivre', 'JV');
INSERT INTO brand (name, code) VALUES ('Jolly Hotels', 'JO');
INSERT INTO brand (name, code) VALUES ('Jurys Doyle Hotel Group', 'JD');
INSERT INTO brand (name, code) VALUES ('Jurys Inns', 'JI');
INSERT INTO brand (name, code) VALUES ('KSL Resorts', 'KO');
INSERT INTO brand (name, code) VALUES ('Karyon', 'MY');
INSERT INTO brand (name, code) VALUES ('Kempinski Hotels & Resorts', 'KI');
INSERT INTO brand (name, code) VALUES ('Keytel', 'KY');
INSERT INTO brand (name, code) VALUES ('Kimpton Hotels', 'KC');
INSERT INTO brand (name, code) VALUES ('Knights Inn', 'KG');
INSERT INTO brand (name, code) VALUES ('Krystal Brand', 'KB');
INSERT INTO brand (name, code) VALUES ('LUXURY HOTELS GROUP', 'LU');
INSERT INTO brand (name, code) VALUES ('LXR Hotels & Resorts', 'OL');
INSERT INTO brand (name, code) VALUES ('Le Meridien', 'MD');
INSERT INTO brand (name, code) VALUES ('Leading Hotels of the World', 'LW');
INSERT INTO brand (name, code) VALUES ('Leela Hotels', 'LR');
INSERT INTO brand (name, code) VALUES ('LeisureLink', 'LI');
INSERT INTO brand (name, code) VALUES ('Leonardo Hotels', 'LD');
INSERT INTO brand (name, code) VALUES ('Lexington Collection', 'LP');
INSERT INTO brand (name, code) VALUES ('Lindner Hotels & Resorts', 'L2');
INSERT INTO brand (name, code) VALUES ('Living Hotels', 'DD');
INSERT INTO brand (name, code) VALUES ('Lucien Barriere', 'LB');
INSERT INTO brand (name, code) VALUES ('Luxe Worldwide Hotels', 'LE');
INSERT INTO brand (name, code) VALUES ('Luxury Lifestyle Hotels & Resorts', 'QX');
INSERT INTO brand (name, code) VALUES ('Luxury Resorts', 'XO');
INSERT INTO brand (name, code) VALUES ('MERCURE - Accor Hotels', 'XM');
INSERT INTO brand (name, code) VALUES ('MGM Grand Hotels', 'MV');
INSERT INTO brand (name, code) VALUES ('MGallery by Sofitel', 'M4');
INSERT INTO brand (name, code) VALUES ('MI Independent Property', 'ZX');
INSERT INTO brand (name, code) VALUES ('Macdonald Hotels', 'GB');
INSERT INTO brand (name, code) VALUES ('Magic Life Hotels', 'AM');
INSERT INTO brand (name, code) VALUES ('Magnolia Hotels and Resorts', 'MG');
INSERT INTO brand (name, code) VALUES ('Magnuson Group', 'MS');
INSERT INTO brand (name, code) VALUES ('Maistra Hotels and Resorts', 'M2');
INSERT INTO brand (name, code) VALUES ('Malmaison Hotels', 'MA');
INSERT INTO brand (name, code) VALUES ('Mandarin Oriental Hotel Group', 'MO');
INSERT INTO brand (name, code) VALUES ('Mantra Hotels', 'MP');
INSERT INTO brand (name, code) VALUES ('Marc Resorts', 'MN');
INSERT INTO brand (name, code) VALUES ('Marco Polo Hotels', 'MH');
INSERT INTO brand (name, code) VALUES ('Maritim Hotels', 'MM');
INSERT INTO brand (name, code) VALUES ('Marriott Authograph Collection', 'AK');
INSERT INTO brand (name, code) VALUES ('Marriott Conference Centers', 'ET');
INSERT INTO brand (name, code) VALUES ('Marriott Hotels, Resorts, and Suites', 'MC');
INSERT INTO brand (name, code) VALUES ('Marriott Vacation Club International', 'VC');
INSERT INTO brand (name, code) VALUES ('Maybourne Hotel Group', 'VY');
INSERT INTO brand (name, code) VALUES ('Meininger Hotels', 'mein');
INSERT INTO brand (name, code) VALUES ('Mercure Gallery', 'ME');
INSERT INTO brand (name, code) VALUES ('Meritus Hotels & Resorts', 'GM');
INSERT INTO brand (name, code) VALUES ('Microtel Inns and Suites', 'MI');
INSERT INTO brand (name, code) VALUES ('Millennium & Copthorne Hotels', 'MU');
INSERT INTO brand (name, code) VALUES ('Morgans Hotel Group', 'MR');
INSERT INTO brand (name, code) VALUES ('Motel One', '1M');
INSERT INTO brand (name, code) VALUES ('Movenpick Hotels & Resorts', 'MK');
INSERT INTO brand (name, code) VALUES ('Myfidelio.net', 'IQ');
INSERT INTO brand (name, code) VALUES ('NOVOTEL - Accor Hotels', 'XN');
INSERT INTO brand (name, code) VALUES ('NOVUM Hotels', 'novum');
INSERT INTO brand (name, code) VALUES ('NWA Collection', 'NA');
INSERT INTO brand (name, code) VALUES ('New Ibis', 'II');
INSERT INTO brand (name, code) VALUES ('New Otani Hotels', 'NO');
INSERT INTO brand (name, code) VALUES ('Nikko Hotels International', 'NK');
INSERT INTO brand (name, code) VALUES ('Noble House', 'NC');
INSERT INTO brand (name, code) VALUES ('Nobu Hotels', 'NB');
INSERT INTO brand (name, code) VALUES ('Northwood Hotels', 'NU');
INSERT INTO brand (name, code) VALUES ('ORBIS', 'OS');
INSERT INTO brand (name, code) VALUES ('OYO HOTELS AND HOMES', 'OY');
INSERT INTO brand (name, code) VALUES ('Oberoi Group of Hotels', '000055');
INSERT INTO brand (name, code) VALUES ('Omni Hotels', 'OM');
INSERT INTO brand (name, code) VALUES ('One and Only Hotels', 'OO');
INSERT INTO brand (name, code) VALUES ('Orient-Express Hotels', 'OE');
INSERT INTO brand (name, code) VALUES ('Othon Hotels', 'OT');
INSERT INTO brand (name, code) VALUES ('Outdoor Traveler Destinations', 'O2');
INSERT INTO brand (name, code) VALUES ('Outrigger Hotels Hawaii', 'OR');
INSERT INTO brand (name, code) VALUES ('Outrigger Hotels Hawaii  OH', 'OH');
INSERT INTO brand (name, code) VALUES ('Palazzo Versace', 'PZ');
INSERT INTO brand (name, code) VALUES ('Pan Pacific Hotels', 'PF');
INSERT INTO brand (name, code) VALUES ('Pan Pacific Hotels and Resorts', 'PP');
INSERT INTO brand (name, code) VALUES ('Park Hotels', 'PG');
INSERT INTO brand (name, code) VALUES ('Park Inn', 'PII');
INSERT INTO brand (name, code) VALUES ('Pegasus Connect', 'UZ');
INSERT INTO brand (name, code) VALUES ('Performance Connections', 'PX');
INSERT INTO brand (name, code) VALUES ('Plaza Pacific Hotels and Resorts', 'GP');
INSERT INTO brand (name, code) VALUES ('Preferred Hotels', 'PH');
INSERT INTO brand (name, code) VALUES ('Premier Connect', 'UA');
INSERT INTO brand (name, code) VALUES ('Premier Inn Hotels', 'prem');
INSERT INTO brand (name, code) VALUES ('Prince Hotels', 'PJ');
INSERT INTO brand (name, code) VALUES ('Principal Hotels', 'PL');
INSERT INTO brand (name, code) VALUES ('Puma Hotels', 'PM');
INSERT INTO brand (name, code) VALUES ('QHOTELS', 'QH');
INSERT INTO brand (name, code) VALUES ('QT Hotels', 'QT');
INSERT INTO brand (name, code) VALUES ('Quality Reservations', 'QR');
INSERT INTO brand (name, code) VALUES ('Queens Moat House Hotels', 'HM');
INSERT INTO brand (name, code) VALUES ('Quest Service Apartments', 'QG');
INSERT INTO brand (name, code) VALUES ('Quorvus Collection', 'QCN');
INSERT INTO brand (name, code) VALUES ('RCI Hotels', 'BQ');
INSERT INTO brand (name, code) VALUES ('REZOnline', 'RO');
INSERT INTO brand (name, code) VALUES ('RIHGA Royal Hotels', 'RR');
INSERT INTO brand (name, code) VALUES ('Radisson Hotels & Resorts', 'RAD');
INSERT INTO brand (name, code) VALUES ('Raffles International Hotels and Resorts', 'YR');
INSERT INTO brand (name, code) VALUES ('Ramada Plazas, Limiteds, and Inns', 'RA');
INSERT INTO brand (name, code) VALUES ('Reconline', 'ON');
INSERT INTO brand (name, code) VALUES ('Red Carnation Hotels', 'RN');
INSERT INTO brand (name, code) VALUES ('Red Lion Hotels & Inns', 'RL');
INSERT INTO brand (name, code) VALUES ('Refad Hotels & Resorts', 'RP');
INSERT INTO brand (name, code) VALUES ('Regal Hotels International', 'RQ');
INSERT INTO brand (name, code) VALUES ('Regent International Hotels', 'REG');
INSERT INTO brand (name, code) VALUES ('Relais & Chateaux', 'WB');
INSERT INTO brand (name, code) VALUES ('Renaissance Hotels and Resorts', 'BR');
INSERT INTO brand (name, code) VALUES ('ReservHOTELs', 'TA');
INSERT INTO brand (name, code) VALUES ('Resort Bookings', 'RB');
INSERT INTO brand (name, code) VALUES ('Resort Quest International', 'QV');
INSERT INTO brand (name, code) VALUES ('ResortQuest Hawaii', 'AH');
INSERT INTO brand (name, code) VALUES ('Rilano Hotels & Resorts', 'rilano');
INSERT INTO brand (name, code) VALUES ('Ringhotels', 'RX');
INSERT INTO brand (name, code) VALUES ('Ritz-Carlton Hotels', 'RZ');
INSERT INTO brand (name, code) VALUES ('Rocco Forte Hotels', 'FC');
INSERT INTO brand (name, code) VALUES ('Rockresorts', 'RS');
INSERT INTO brand (name, code) VALUES ('Romantik Hotels International', 'RM');
INSERT INTO brand (name, code) VALUES ('Rotana Hotels', 'R2');
INSERT INTO brand (name, code) VALUES ('Rydges Hotels', 'RG');
INSERT INTO brand (name, code) VALUES ('SOFITEL - Accor Hotels and Resorts', 'VS');
INSERT INTO brand (name, code) VALUES ('STARHOTELS', 'SY');
INSERT INTO brand (name, code) VALUES ('SUITE HOTELS - Accor Hotels', 'XA');
INSERT INTO brand (name, code) VALUES ('Safir Hotels & Resorts', 'EF');
INSERT INTO brand (name, code) VALUES ('Sandals Resorts', 'JS');
INSERT INTO brand (name, code) VALUES ('Sandman Hotels', 'PS');
INSERT INTO brand (name, code) VALUES ('Sarova Hotels', 'SA');
INSERT INTO brand (name, code) VALUES ('Scandic Hotels', 'SH');
INSERT INTO brand (name, code) VALUES ('Sceptre', 'SC');
INSERT INTO brand (name, code) VALUES ('Sercotel Hoteles Independientes', 'SX');
INSERT INTO brand (name, code) VALUES ('Serviced Apartments Worldwide', 'A1');
INSERT INTO brand (name, code) VALUES ('Shangri-La Hotels and Resorts', 'SG');
INSERT INTO brand (name, code) VALUES ('Sheraton Hotels and Resorts', 'SI');
INSERT INTO brand (name, code) VALUES ('Shilo Resorts', 'BP');
INSERT INTO brand (name, code) VALUES ('Sierra Suites Hotels', 'US');
INSERT INTO brand (name, code) VALUES ('Signature/Jameson Inns', 'SJ');
INSERT INTO brand (name, code) VALUES ('SilverNeedle', 'S5');
INSERT INTO brand (name, code) VALUES ('Six Senses', 'IG');
INSERT INTO brand (name, code) VALUES ('Six Senses Resorts & Spas', 'GR');
INSERT INTO brand (name, code) VALUES ('Sixty Hotels', 'S7');
INSERT INTO brand (name, code) VALUES ('Small Luxury Hotels of the World', '000194');
INSERT INTO brand (name, code) VALUES ('So Sofitel', 'S9');
INSERT INTO brand (name, code) VALUES ('Sofitel Hotels & Resorts', 'SF');
INSERT INTO brand (name, code) VALUES ('Sokos Hotels', 'SK');
INSERT INTO brand (name, code) VALUES ('Sol Melia', 'SM');
INSERT INTO brand (name, code) VALUES ('Sonesta Hotels and Resorts', 'SN');
INSERT INTO brand (name, code) VALUES ('Special Properties of InterContinental Hotels', 'SP');
INSERT INTO brand (name, code) VALUES ('St. Regis Luxury Collection', 'LX');
INSERT INTO brand (name, code) VALUES ('Staybridge Suites by Holiday Inn', 'SB');
INSERT INTO brand (name, code) VALUES ('Steigenberger', 'S1');
INSERT INTO brand (name, code) VALUES ('Sterling Hotels and Resorts', 'WR');
INSERT INTO brand (name, code) VALUES ('Suburban Hotels', 'UB');
INSERT INTO brand (name, code) VALUES ('Summit Hotels and Resorts', 'XL');
INSERT INTO brand (name, code) VALUES ('Super 8 Motels', 'SE');
INSERT INTO brand (name, code) VALUES ('SuperClubs', 'SR');
INSERT INTO brand (name, code) VALUES ('Supranational Hotels', 'ZS');
INSERT INTO brand (name, code) VALUES ('SureStay Hotels', 'UR');
INSERT INTO brand (name, code) VALUES ('Swiss Quality Hotels International', 'QO');
INSERT INTO brand (name, code) VALUES ('Switzerland Travel Centre', 'SD');
INSERT INTO brand (name, code) VALUES ('Synxis', 'YX');
INSERT INTO brand (name, code) VALUES ('TOP International Hotels', 'TP');
INSERT INTO brand (name, code) VALUES ('TShotels', 'TS');
INSERT INTO brand (name, code) VALUES ('TUI Hotels', 'TU');
INSERT INTO brand (name, code) VALUES ('Taj Hotels, Resorts & Palaces', 'TJ');
INSERT INTO brand (name, code) VALUES ('The Ascott Limited', 'A3');
INSERT INTO brand (name, code) VALUES ('The Charming Hotels of the World', 'CU');
INSERT INTO brand (name, code) VALUES ('The Lalit', 'LJ');
INSERT INTO brand (name, code) VALUES ('The Regency Hotel Group', 'RE');
INSERT INTO brand (name, code) VALUES ('The Small Hotel Company', 'SO');
INSERT INTO brand (name, code) VALUES ('The Sutton Place Hotels', '000063');
INSERT INTO brand (name, code) VALUES ('Thistle Hotels', 'TI');
INSERT INTO brand (name, code) VALUES ('Thompson Hotels', 'TM');
INSERT INTO brand (name, code) VALUES ('Thon Hotels', 'TF');
INSERT INTO brand (name, code) VALUES ('Toga Hotels', 'T2');
INSERT INTO brand (name, code) VALUES ('Tommie Hotels', 'I2');
INSERT INTO brand (name, code) VALUES ('TourOnline', 'TQ');
INSERT INTO brand (name, code) VALUES ('Trademark Collection', 'TC');
INSERT INTO brand (name, code) VALUES ('Tradyso', 'TY');
INSERT INTO brand (name, code) VALUES ('TravLynx', 'IL');
INSERT INTO brand (name, code) VALUES ('TravelCLICK', 'WV');
INSERT INTO brand (name, code) VALUES ('TravelTripper', 'XT');
INSERT INTO brand (name, code) VALUES ('TravelWeb LLC', 'HS');
INSERT INTO brand (name, code) VALUES ('Travelodge UK', 'TG');
INSERT INTO brand (name, code) VALUES ('Trump Hotel Collection', 'TW');
INSERT INTO brand (name, code) VALUES ('Trust Hospitality', 'YT');
INSERT INTO brand (name, code) VALUES ('Tryp Hotels', 'WT');
INSERT INTO brand (name, code) VALUES ('Unique Hotels', 'OG');
INSERT INTO brand (name, code) VALUES ('Universal', 'UE');
INSERT INTO brand (name, code) VALUES ('Universal Partners', 'UP');
INSERT INTO brand (name, code) VALUES ('Utell', 'UI');
INSERT INTO brand (name, code) VALUES ('Vagabond Inns', 'VA');
INSERT INTO brand (name, code) VALUES ('Vantis Hotels Group', 'LM');
INSERT INTO brand (name, code) VALUES ('Viceroy Hotel Group', 'VG');
INSERT INTO brand (name, code) VALUES ('Vienna International', 'VI');
INSERT INTO brand (name, code) VALUES ('Villager', 'VL');
INSERT INTO brand (name, code) VALUES ('Voco', 'VX');
INSERT INTO brand (name, code) VALUES ('WLB Hotels', 'PW');
INSERT INTO brand (name, code) VALUES ('WORLDHOTELS', 'SW');
INSERT INTO brand (name, code) VALUES ('Warwick International Hotels', 'WK');
INSERT INTO brand (name, code) VALUES ('Webres', 'XW');
INSERT INTO brand (name, code) VALUES ('Wingate Inns', 'WG');
INSERT INTO brand (name, code) VALUES ('Woodfin Suites', 'WD');
INSERT INTO brand (name, code) VALUES ('WorldHotels United', 'U1');
INSERT INTO brand (name, code) VALUES ('Wyndham Extra Holidays', 'WO');
INSERT INTO brand (name, code) VALUES ('Wyndham Hotels and Resorts', 'WY');
INSERT INTO brand (name, code) VALUES ('XN Corporation', 'XG');
INSERT INTO brand (name, code) VALUES ('Yotel Hotels', 'YL');
INSERT INTO brand (name, code) VALUES ('Your Hotel Worldwide', 'YH');
